/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apiseguradora);
  }
}(this, function(expect, Apiseguradora) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Apiseguradora.CapitalSeguradoAcumuladoApi();
  });

  describe('(package)', function() {
    describe('CapitalSeguradoAcumuladoApi', function() {
      describe('apiversionCapitalSeguradoAcumuladocnpjcnpjcodigoModeloPropostacodigoModeloPropostaPOST', function() {
        it('should call apiversionCapitalSeguradoAcumuladocnpjcnpjcodigoModeloPropostacodigoModeloPropostaPOST successfully', function(done) {
          // TODO: uncomment, update parameter values for apiversionCapitalSeguradoAcumuladocnpjcnpjcodigoModeloPropostacodigoModeloPropostaPOST call and complete the assertions
          /*
          var pesquisa = new Apiseguradora.APISeguradoraContratoV1CapitalSeguradoAcumuladoCapitalSeguradoAcumuladoPesquisa();
          pesquisa.cpf = "";
          pesquisa.dataNascimento = new Date();
          var cnpj = "cnpj_example";
          var codigoModeloProposta = "codigoModeloProposta_example";
          var version = "version_example";
          var authorization = "authorization_example";

          instance.apiversionCapitalSeguradoAcumuladocnpjcnpjcodigoModeloPropostacodigoModeloPropostaPOST(pesquisa, cnpj, codigoModeloProposta, version, authorization, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Apiseguradora.APISeguradoraHelperResultadoDaOperacaoRestAPISeguradoraContratoV1CapitalSeguradoAcumuladoResultadoCapitalSeguradoAcumulado);
            expect(data.valor).to.be.a(Apiseguradora.APISeguradoraContratoV1CapitalSeguradoAcumuladoResultadoCapitalSeguradoAcumulado);
                  {
                let dataCtr = data.valor.capitaisSegurados;
                expect(dataCtr).to.be.an(Array);
                expect(dataCtr).to.not.be.empty();
                for (let p in dataCtr) {
                  let data = dataCtr[p];
                  expect(data).to.be.a(Apiseguradora.APISeguradoraContratoV1CapitalSeguradoAcumuladoCapitalSeguradoAcumulado);
                  expect(data.causa).to.be.a('string');
                  expect(data.causa).to.be("");
                  expect(data.valor).to.be.a('number');
                  expect(data.valor).to.be(0.0);
                }
              }
            {
              let dataCtr = data.mensagens;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a('string');
                expect(data).to.be("");
              }
            }
            expect(data.houveErrosDuranteProcessamento).to.be.a('boolean');
            expect(data.houveErrosDuranteProcessamento).to.be(false);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
