/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apiseguradora);
  }
}(this, function(expect, Apiseguradora) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Apiseguradora.PendenciaApi();
  });

  describe('(package)', function() {
    describe('PendenciaApi', function() {
      describe('apiversionpendenciacnpjcnpjPUT', function() {
        it('should call apiversionpendenciacnpjcnpjPUT successfully', function(done) {
          // TODO: uncomment, update parameter values for apiversionpendenciacnpjcnpjPUT call and complete the assertions
          /*
          var pendencia = new Apiseguradora.APISeguradoraContratoV1PendenciaPendencia();
          pendencia.id = "0";
          pendencia.idProposta = "0";
          pendencia.dataPendencia = new Date();
          pendencia.responsavel = "";
          pendencia.grupo = "";
          pendencia.descricao = "";
          pendencia.resposta = "";
          pendencia.autor = "";
          pendencia.documento = new Apiseguradora.APISeguradoraContratoV1DocDocumento();
          pendencia.documento.id = "";
          pendencia.documento.dataDocumento = new Date();
          pendencia.documento.formato = "";
          pendencia.documento.grupoDocumento = "";
          pendencia.documento.qtdePaginas = 0;
          pendencia.documento.tipoDocumento = "";
          pendencia.documento.nomeArquivo = "";
          pendencia.documento.indicesDocumento = [new Apiseguradora.APISeguradoraContratoV1DocIndiceDocumento()];
          pendencia.documento.indicesDocumento[0].valor = "";
          pendencia.documento.indicesDocumento[0].tipoIndice = "";
          pendencia.documento.pagina = [new Apiseguradora.APISeguradoraContratoV1DocDocumentoPagina()];
          pendencia.documento.pagina[0].pagina = 0;
          pendencia.documento.pagina[0].dados = [""];
          var cnpj = "cnpj_example";
          var version = "version_example";
          var authorization = "authorization_example";

          instance.apiversionpendenciacnpjcnpjPUT(pendencia, cnpj, version, authorization, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Apiseguradora.APISeguradoraHelperResultadoDaOperacaoRestAPISeguradoraContratoV1PendenciaPendencia);
            expect(data.valor).to.be.a(Apiseguradora.APISeguradoraContratoV1PendenciaPendencia);
                  expect(data.valor.id).to.be.a('number');
              expect(data.valor.id).to.be("0");
              expect(data.valor.idProposta).to.be.a('number');
              expect(data.valor.idProposta).to.be("0");
              expect(data.valor.dataPendencia).to.be.a(Date);
              expect(data.valor.dataPendencia).to.be(new Date());
              expect(data.valor.responsavel).to.be.a('string');
              expect(data.valor.responsavel).to.be("");
              expect(data.valor.grupo).to.be.a('string');
              expect(data.valor.grupo).to.be("");
              expect(data.valor.descricao).to.be.a('string');
              expect(data.valor.descricao).to.be("");
              expect(data.valor.resposta).to.be.a('string');
              expect(data.valor.resposta).to.be("");
              expect(data.valor.autor).to.be.a('string');
              expect(data.valor.autor).to.be("");
              expect(data.valor.documento).to.be.a(Apiseguradora.APISeguradoraContratoV1DocDocumento);
                    expect(data.valor.documento.id).to.be.a('string');
                expect(data.valor.documento.id).to.be("");
                expect(data.valor.documento.dataDocumento).to.be.a(Date);
                expect(data.valor.documento.dataDocumento).to.be(new Date());
                expect(data.valor.documento.formato).to.be.a('string');
                expect(data.valor.documento.formato).to.be("");
                expect(data.valor.documento.grupoDocumento).to.be.a('string');
                expect(data.valor.documento.grupoDocumento).to.be("");
                expect(data.valor.documento.qtdePaginas).to.be.a('number');
                expect(data.valor.documento.qtdePaginas).to.be(0);
                expect(data.valor.documento.tipoDocumento).to.be.a('string');
                expect(data.valor.documento.tipoDocumento).to.be("");
                expect(data.valor.documento.nomeArquivo).to.be.a('string');
                expect(data.valor.documento.nomeArquivo).to.be("");
                {
                  let dataCtr = data.valor.documento.indicesDocumento;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a(Apiseguradora.APISeguradoraContratoV1DocIndiceDocumento);
                    expect(data.valor).to.be.a('string');
                    expect(data.valor).to.be("");
                    expect(data.tipoIndice).to.be.a('string');
                    expect(data.tipoIndice).to.be("");
                  }
                }
                {
                  let dataCtr = data.valor.documento.pagina;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a(Apiseguradora.APISeguradoraContratoV1DocDocumentoPagina);
                    expect(data.pagina).to.be.a('number');
                    expect(data.pagina).to.be(0);
                    {
                      let dataCtr = data.dados;
                      expect(dataCtr).to.be.an(Array);
                      expect(dataCtr).to.not.be.empty();
                      for (let p in dataCtr) {
                        let data = dataCtr[p];
                        expect(data).to.be.a('string');
                        expect(data).to.be("");
                      }
                    }
                  }
                }
            {
              let dataCtr = data.mensagens;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a('string');
                expect(data).to.be("");
              }
            }
            expect(data.houveErrosDuranteProcessamento).to.be.a('boolean');
            expect(data.houveErrosDuranteProcessamento).to.be(false);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiversionpendenciacnpjcnpjnumeroPropostanumeroPropostaGET', function() {
        it('should call apiversionpendenciacnpjcnpjnumeroPropostanumeroPropostaGET successfully', function(done) {
          // TODO: uncomment, update parameter values for apiversionpendenciacnpjcnpjnumeroPropostanumeroPropostaGET call and complete the assertions
          /*
          var cnpj = "cnpj_example";
          var numeroProposta = 789;
          var version = "version_example";
          var authorization = "authorization_example";

          instance.apiversionpendenciacnpjcnpjnumeroPropostanumeroPropostaGET(cnpj, numeroProposta, version, authorization, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Apiseguradora.APISeguradoraHelperResultadoDaOperacaoRestSystemLinqIQueryableAPISeguradoraContratoV1PendenciaPendencia);
            {
              let dataCtr = data.valor;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(Apiseguradora.APISeguradoraContratoV1PendenciaPendencia);
                expect(data.id).to.be.a('number');
                expect(data.id).to.be("0");
                expect(data.idProposta).to.be.a('number');
                expect(data.idProposta).to.be("0");
                expect(data.dataPendencia).to.be.a(Date);
                expect(data.dataPendencia).to.be(new Date());
                expect(data.responsavel).to.be.a('string');
                expect(data.responsavel).to.be("");
                expect(data.grupo).to.be.a('string');
                expect(data.grupo).to.be("");
                expect(data.descricao).to.be.a('string');
                expect(data.descricao).to.be("");
                expect(data.resposta).to.be.a('string');
                expect(data.resposta).to.be("");
                expect(data.autor).to.be.a('string');
                expect(data.autor).to.be("");
                expect(data.documento).to.be.a(Apiseguradora.APISeguradoraContratoV1DocDocumento);
                      expect(data.documento.id).to.be.a('string');
                  expect(data.documento.id).to.be("");
                  expect(data.documento.dataDocumento).to.be.a(Date);
                  expect(data.documento.dataDocumento).to.be(new Date());
                  expect(data.documento.formato).to.be.a('string');
                  expect(data.documento.formato).to.be("");
                  expect(data.documento.grupoDocumento).to.be.a('string');
                  expect(data.documento.grupoDocumento).to.be("");
                  expect(data.documento.qtdePaginas).to.be.a('number');
                  expect(data.documento.qtdePaginas).to.be(0);
                  expect(data.documento.tipoDocumento).to.be.a('string');
                  expect(data.documento.tipoDocumento).to.be("");
                  expect(data.documento.nomeArquivo).to.be.a('string');
                  expect(data.documento.nomeArquivo).to.be("");
                  {
                    let dataCtr = data.documento.indicesDocumento;
                    expect(dataCtr).to.be.an(Array);
                    expect(dataCtr).to.not.be.empty();
                    for (let p in dataCtr) {
                      let data = dataCtr[p];
                      expect(data).to.be.a(Apiseguradora.APISeguradoraContratoV1DocIndiceDocumento);
                      expect(data.valor).to.be.a('string');
                      expect(data.valor).to.be("");
                      expect(data.tipoIndice).to.be.a('string');
                      expect(data.tipoIndice).to.be("");
                    }
                  }
                  {
                    let dataCtr = data.documento.pagina;
                    expect(dataCtr).to.be.an(Array);
                    expect(dataCtr).to.not.be.empty();
                    for (let p in dataCtr) {
                      let data = dataCtr[p];
                      expect(data).to.be.a(Apiseguradora.APISeguradoraContratoV1DocDocumentoPagina);
                      expect(data.pagina).to.be.a('number');
                      expect(data.pagina).to.be(0);
                      {
                        let dataCtr = data.dados;
                        expect(dataCtr).to.be.an(Array);
                        expect(dataCtr).to.not.be.empty();
                        for (let p in dataCtr) {
                          let data = dataCtr[p];
                          expect(data).to.be.a('string');
                          expect(data).to.be("");
                        }
                      }
                    }
                  }
              }
            }
            {
              let dataCtr = data.mensagens;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a('string');
                expect(data).to.be("");
              }
            }
            expect(data.houveErrosDuranteProcessamento).to.be.a('boolean');
            expect(data.houveErrosDuranteProcessamento).to.be(false);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
