/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apiseguradora);
  }
}(this, function(expect, Apiseguradora) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Apiseguradora.PoliticaAceitacaoApi();
  });

  describe('(package)', function() {
    describe('PoliticaAceitacaoApi', function() {
      describe('apiversionpoliticaAceitacaocnpjcnpjGET', function() {
        it('should call apiversionpoliticaAceitacaocnpjcnpjGET successfully', function(done) {
          // TODO: uncomment, update parameter values for apiversionpoliticaAceitacaocnpjcnpjGET call and complete the assertions
          /*
          var cnpj = "cnpj_example";
          var version = "version_example";
          var authorization = "authorization_example";

          instance.apiversionpoliticaAceitacaocnpjcnpjGET(cnpj, version, authorization, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Apiseguradora.APISeguradoraHelperResultadoDaOperacaoRestSystemLinqIQueryableAPISeguradoraContratoV1PoliticaAceitacaoPoliticaAceitacao);
            {
              let dataCtr = data.valor;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(Apiseguradora.APISeguradoraContratoV1PoliticaAceitacaoPoliticaAceitacao);
                expect(data.id).to.be.a('number');
                expect(data.id).to.be(0);
                expect(data.dataUltimaAlteracao).to.be.a(Date);
                expect(data.dataUltimaAlteracao).to.be(new Date());
                expect(data.imcMinimoRecusa).to.be.a('number');
                expect(data.imcMinimoRecusa).to.be(0);
                expect(data.imcMaximoRecusa).to.be.a('number');
                expect(data.imcMaximoRecusa).to.be(0);
                expect(data.imcMinimoExame).to.be.a('number');
                expect(data.imcMinimoExame).to.be(0);
                expect(data.imcMaximoExame).to.be.a('number');
                expect(data.imcMaximoExame).to.be(0);
                expect(data.cigarrosRecusa).to.be.a('number');
                expect(data.cigarrosRecusa).to.be(0);
                expect(data.cigarrosExame).to.be.a('number');
                expect(data.cigarrosExame).to.be(0);
                {
                  let dataCtr = data.limitesOperacionaisPorProfissao;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a(Apiseguradora.APISeguradoraContratoV1PoliticaAceitacaoLimiteOperacionalProfissao);
                    expect(data.causa).to.be.a('string');
                    expect(data.causa).to.be("");
                    expect(data.profissaoId).to.be.a('number');
                    expect(data.profissaoId).to.be(0);
                    expect(data.valorMaximoCapitalSegurado).to.be.a('number');
                    expect(data.valorMaximoCapitalSegurado).to.be(0.0);
                  }
                }
                {
                  let dataCtr = data.limitesOperacionaisPorRenda;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a(Apiseguradora.APISeguradoraContratoV1PoliticaAceitacaoLimiteOperacionalRenda);
                    expect(data.causa).to.be.a('string');
                    expect(data.causa).to.be("");
                    expect(data.idadeInicial).to.be.a('number');
                    expect(data.idadeInicial).to.be(0);
                    expect(data.idadeFinal).to.be.a('number');
                    expect(data.idadeFinal).to.be(0);
                    expect(data.multiploRenda).to.be.a('number');
                    expect(data.multiploRenda).to.be(0);
                  }
                }
                {
                  let dataCtr = data.limitesOperacionaisPorFaixaEtaria;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a(Apiseguradora.APISeguradoraContratoV1PoliticaAceitacaoLimiteOperacionalFaixaEtaria);
                    expect(data.causa).to.be.a('string');
                    expect(data.causa).to.be("");
                    expect(data.idadeInicial).to.be.a('number');
                    expect(data.idadeInicial).to.be(0);
                    expect(data.idadeFinal).to.be.a('number');
                    expect(data.idadeFinal).to.be(0);
                    expect(data.valorMaximoCapitalSegurado).to.be.a('number');
                    expect(data.valorMaximoCapitalSegurado).to.be(0);
                  }
                }
              }
            }
            {
              let dataCtr = data.mensagens;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a('string');
                expect(data).to.be("");
              }
            }
            expect(data.houveErrosDuranteProcessamento).to.be.a('boolean');
            expect(data.houveErrosDuranteProcessamento).to.be(false);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
