/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apiseguradora);
  }
}(this, function(expect, Apiseguradora) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Apiseguradora.RegraComissaoApi();
  });

  describe('(package)', function() {
    describe('RegraComissaoApi', function() {
      describe('apiversionRegraComissaoidGET', function() {
        it('should call apiversionRegraComissaoidGET successfully', function(done) {
          // TODO: uncomment, update parameter values for apiversionRegraComissaoidGET call and complete the assertions
          /*
          var id = 789;
          var version = "version_example";
          var authorization = "authorization_example";

          instance.apiversionRegraComissaoidGET(id, version, authorization, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Apiseguradora.APISeguradoraHelperResultadoDaOperacaoRestSystemCollectionsGenericListAPISeguradoraImplementacaoServicoServicoRegraComissaoDadosComissionamentoTransformado);
            {
              let dataCtr = data.valor;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(Apiseguradora.APISeguradoraImplementacaoServicoServicoRegraComissaoDadosComissionamentoTransformado);
                expect(data.nome).to.be.a('string');
                expect(data.nome).to.be("");
                expect(data.tipoComissionamento).to.be.a('string');
                expect(data.tipoComissionamento).to.be("");
                expect(data.detalheComissionamento).to.be.a('string');
                expect(data.detalheComissionamento).to.be("");
                expect(data.tipoPessoa).to.be.a('string');
                expect(data.tipoPessoa).to.be("");
                expect(data.numeroAlternativa).to.be.a('number');
                expect(data.numeroAlternativa).to.be(0);
                expect(data.DG).to.be.a('string');
                expect(data.DG).to.be("");
                {
                  let dataCtr = data.comissionamentos;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a(Apiseguradora.APISeguradoraImplementacaoServicoServicoRegraComissaoComissionamento);
                    expect(data.tipoComissionamento).to.be.a('string');
                    expect(data.tipoComissionamento).to.be("");
                    expect(data.percentual).to.be.a('number');
                    expect(data.percentual).to.be(0.0);
                    expect(data.periodicidade).to.be.a('number');
                    expect(data.periodicidade).to.be(0);
                  }
                }
                {
                  let dataCtr = data.faixasPercentuais;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a(Apiseguradora.APISeguradoraImplementacaoComissoesCondicaoComercialFaixaPercentual);
                    expect(data.tipoAngariacao).to.be.a('string');
                    expect(data.tipoAngariacao).to.be("");
                    expect(data.tipoFatoGeradorComissao).to.be.a('string');
                    expect(data.tipoFatoGeradorComissao).to.be("");
                    expect(data.tipoFaixaPercentual).to.be.a('string');
                    expect(data.tipoFaixaPercentual).to.be("");
                    expect(data.valorInicial).to.be.a('number');
                    expect(data.valorInicial).to.be(0.0);
                    expect(data.valorFinal).to.be.a('number');
                    expect(data.valorFinal).to.be(0.0);
                    expect(data.percentual).to.be.a('number');
                    expect(data.percentual).to.be(0.0);
                    expect(data.periodicidade).to.be.a('number');
                    expect(data.periodicidade).to.be(0);
                    expect(data.valorMinimo).to.be.a('number');
                    expect(data.valorMinimo).to.be(0.0);
                  }
                }
              }
            }
            {
              let dataCtr = data.mensagens;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a('string');
                expect(data).to.be("");
              }
            }
            expect(data.houveErrosDuranteProcessamento).to.be.a('boolean');
            expect(data.houveErrosDuranteProcessamento).to.be(false);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
