/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apiseguradora);
  }
}(this, function(expect, Apiseguradora) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Apiseguradora.TimeLineApi();
  });

  describe('(package)', function() {
    describe('TimeLineApi', function() {
      describe('apiversiontimelinecnpjcnpjnumeroPropostanumeroPropostaGET', function() {
        it('should call apiversiontimelinecnpjcnpjnumeroPropostanumeroPropostaGET successfully', function(done) {
          // TODO: uncomment, update parameter values for apiversiontimelinecnpjcnpjnumeroPropostanumeroPropostaGET call and complete the assertions
          /*
          var cnpj = "cnpj_example";
          var numeroProposta = 789;
          var version = "version_example";
          var authorization = "authorization_example";

          instance.apiversiontimelinecnpjcnpjnumeroPropostanumeroPropostaGET(cnpj, numeroProposta, version, authorization, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Apiseguradora.APISeguradoraHelperResultadoDaOperacaoRestSystemLinqIQueryableAPISeguradoraContratoV1TimeLineTimeLine);
            {
              let dataCtr = data.valor;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(Apiseguradora.APISeguradoraContratoV1TimeLineTimeLine);
                expect(data.data).to.be.a(Date);
                expect(data.data).to.be(new Date());
                expect(data.status).to.be.a('string');
                expect(data.status).to.be("");
                expect(data.usuario).to.be.a('string');
                expect(data.usuario).to.be("");
                {
                  let dataCtr = data.pendencias;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a(Apiseguradora.APISeguradoraContratoV1PendenciaPendencia);
                    expect(data.id).to.be.a('number');
                    expect(data.id).to.be("0");
                    expect(data.idProposta).to.be.a('number');
                    expect(data.idProposta).to.be("0");
                    expect(data.dataPendencia).to.be.a(Date);
                    expect(data.dataPendencia).to.be(new Date());
                    expect(data.responsavel).to.be.a('string');
                    expect(data.responsavel).to.be("");
                    expect(data.grupo).to.be.a('string');
                    expect(data.grupo).to.be("");
                    expect(data.descricao).to.be.a('string');
                    expect(data.descricao).to.be("");
                    expect(data.resposta).to.be.a('string');
                    expect(data.resposta).to.be("");
                    expect(data.autor).to.be.a('string');
                    expect(data.autor).to.be("");
                    expect(data.documento).to.be.a(Apiseguradora.APISeguradoraContratoV1DocDocumento);
                          expect(data.documento.id).to.be.a('string');
                      expect(data.documento.id).to.be("");
                      expect(data.documento.dataDocumento).to.be.a(Date);
                      expect(data.documento.dataDocumento).to.be(new Date());
                      expect(data.documento.formato).to.be.a('string');
                      expect(data.documento.formato).to.be("");
                      expect(data.documento.grupoDocumento).to.be.a('string');
                      expect(data.documento.grupoDocumento).to.be("");
                      expect(data.documento.qtdePaginas).to.be.a('number');
                      expect(data.documento.qtdePaginas).to.be(0);
                      expect(data.documento.tipoDocumento).to.be.a('string');
                      expect(data.documento.tipoDocumento).to.be("");
                      expect(data.documento.nomeArquivo).to.be.a('string');
                      expect(data.documento.nomeArquivo).to.be("");
                      {
                        let dataCtr = data.documento.indicesDocumento;
                        expect(dataCtr).to.be.an(Array);
                        expect(dataCtr).to.not.be.empty();
                        for (let p in dataCtr) {
                          let data = dataCtr[p];
                          expect(data).to.be.a(Apiseguradora.APISeguradoraContratoV1DocIndiceDocumento);
                          expect(data.valor).to.be.a('string');
                          expect(data.valor).to.be("");
                          expect(data.tipoIndice).to.be.a('string');
                          expect(data.tipoIndice).to.be("");
                        }
                      }
                      {
                        let dataCtr = data.documento.pagina;
                        expect(dataCtr).to.be.an(Array);
                        expect(dataCtr).to.not.be.empty();
                        for (let p in dataCtr) {
                          let data = dataCtr[p];
                          expect(data).to.be.a(Apiseguradora.APISeguradoraContratoV1DocDocumentoPagina);
                          expect(data.pagina).to.be.a('number');
                          expect(data.pagina).to.be(0);
                          {
                            let dataCtr = data.dados;
                            expect(dataCtr).to.be.an(Array);
                            expect(dataCtr).to.not.be.empty();
                            for (let p in dataCtr) {
                              let data = dataCtr[p];
                              expect(data).to.be.a('string');
                              expect(data).to.be("");
                            }
                          }
                        }
                      }
                  }
                }
                expect(data.agendamentosMedicos).to.be.a(Apiseguradora.APISeguradoraContratoV1PropostaAgendamentoMedico);
                      {
                    let dataCtr = data.agendamentosMedicos.chamadas;
                    expect(dataCtr).to.be.an(Array);
                    expect(dataCtr).to.not.be.empty();
                    for (let p in dataCtr) {
                      let data = dataCtr[p];
                      expect(data).to.be.a(Apiseguradora.APISeguradoraContratoV1PropostaChamadas);
                      expect(data.datahora).to.be.a(Date);
                      expect(data.datahora).to.be(new Date());
                      expect(data.motivo).to.be.a('string');
                      expect(data.motivo).to.be("");
                      expect(data.descricao).to.be.a('string');
                      expect(data.descricao).to.be("");
                    }
                  }
                  {
                    let dataCtr = data.agendamentosMedicos.notificacoes;
                    expect(dataCtr).to.be.an(Array);
                    expect(dataCtr).to.not.be.empty();
                    for (let p in dataCtr) {
                      let data = dataCtr[p];
                      expect(data).to.be.a(Apiseguradora.APISeguradoraContratoV1PropostaNotificacoes);
                      expect(data.texto).to.be.a('string');
                      expect(data.texto).to.be("");
                      expect(data.datahora).to.be.a(Date);
                      expect(data.datahora).to.be(new Date());
                    }
                  }
                  {
                    let dataCtr = data.agendamentosMedicos.situacoes;
                    expect(dataCtr).to.be.an(Array);
                    expect(dataCtr).to.not.be.empty();
                    for (let p in dataCtr) {
                      let data = dataCtr[p];
                      expect(data).to.be.a(Apiseguradora.APISeguradoraContratoV1PropostaSituacoes);
                      expect(data.descricao).to.be.a('string');
                      expect(data.descricao).to.be("");
                      expect(data.datahora).to.be.a(Date);
                      expect(data.datahora).to.be(new Date());
                    }
                  }
              }
            }
            {
              let dataCtr = data.mensagens;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a('string');
                expect(data).to.be("");
              }
            }
            expect(data.houveErrosDuranteProcessamento).to.be.a('boolean');
            expect(data.houveErrosDuranteProcessamento).to.be(false);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
