/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/APISeguradoraContratoV1PropostaCheque'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./APISeguradoraContratoV1PropostaCheque'));
  } else {
    // Browser globals (root is window)
    if (!root.Apiseguradora) {
      root.Apiseguradora = {};
    }
    root.Apiseguradora.APISeguradoraContratoV1PropostaReciboPrimeiroPagamento = factory(root.Apiseguradora.ApiClient, root.Apiseguradora.APISeguradoraContratoV1PropostaCheque);
  }
}(this, function(ApiClient, APISeguradoraContratoV1PropostaCheque) {
  'use strict';

  /**
   * The APISeguradoraContratoV1PropostaReciboPrimeiroPagamento model module.
   * @module model/APISeguradoraContratoV1PropostaReciboPrimeiroPagamento
   * @version v1
   */

  /**
   * Constructs a new <code>APISeguradoraContratoV1PropostaReciboPrimeiroPagamento</code>.
   * @alias module:model/APISeguradoraContratoV1PropostaReciboPrimeiroPagamento
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>APISeguradoraContratoV1PropostaReciboPrimeiroPagamento</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APISeguradoraContratoV1PropostaReciboPrimeiroPagamento} obj Optional instance to populate.
   * @return {module:model/APISeguradoraContratoV1PropostaReciboPrimeiroPagamento} The populated <code>APISeguradoraContratoV1PropostaReciboPrimeiroPagamento</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('TipoPagamento'))
        obj.tipoPagamento = ApiClient.convertToType(data['TipoPagamento'], 'String');
      if (data.hasOwnProperty('Valor'))
        obj.valor = ApiClient.convertToType(data['Valor'], 'String');
      if (data.hasOwnProperty('NmPagador'))
        obj.nmPagador = ApiClient.convertToType(data['NmPagador'], 'String');
      if (data.hasOwnProperty('CpfPagador'))
        obj.cpfPagador = ApiClient.convertToType(data['CpfPagador'], 'Number');
      if (data.hasOwnProperty('Cheque'))
        obj.cheque = APISeguradoraContratoV1PropostaCheque.constructFromObject(data['Cheque']);
    }
    return obj;
  }

  /**
   * @member {String} tipoPagamento
   */
  exports.prototype.tipoPagamento = undefined;

  /**
   * @member {String} valor
   */
  exports.prototype.valor = undefined;

  /**
   * @member {String} nmPagador
   */
  exports.prototype.nmPagador = undefined;

  /**
   * @member {Number} cpfPagador
   */
  exports.prototype.cpfPagador = undefined;

  /**
   * @member {module:model/APISeguradoraContratoV1PropostaCheque} cheque
   */
  exports.prototype.cheque = undefined;

  return exports;

}));
