/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/APISeguradoraImplementacaoESimProdutoCloneNegociacaoPoliticaRelacionamentoaDTO', 'model/APISeguradoraImplementacaoESimProdutoCloneNegociacaoProdutoNegociaoDTO', 'model/APISeguradoraImplementacaoESimProdutoCloneNegociacaoTeleUnderwritingDTO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./APISeguradoraImplementacaoESimProdutoCloneNegociacaoPoliticaRelacionamentoaDTO'), require('./APISeguradoraImplementacaoESimProdutoCloneNegociacaoProdutoNegociaoDTO'), require('./APISeguradoraImplementacaoESimProdutoCloneNegociacaoTeleUnderwritingDTO'));
  } else {
    // Browser globals (root is window)
    if (!root.Apiseguradora) {
      root.Apiseguradora = {};
    }
    root.Apiseguradora.APISeguradoraImplementacaoESimProdutoCloneNegociacaoNegociacaoDTO = factory(root.Apiseguradora.ApiClient, root.Apiseguradora.APISeguradoraImplementacaoESimProdutoCloneNegociacaoPoliticaRelacionamentoaDTO, root.Apiseguradora.APISeguradoraImplementacaoESimProdutoCloneNegociacaoProdutoNegociaoDTO, root.Apiseguradora.APISeguradoraImplementacaoESimProdutoCloneNegociacaoTeleUnderwritingDTO);
  }
}(this, function(ApiClient, APISeguradoraImplementacaoESimProdutoCloneNegociacaoPoliticaRelacionamentoaDTO, APISeguradoraImplementacaoESimProdutoCloneNegociacaoProdutoNegociaoDTO, APISeguradoraImplementacaoESimProdutoCloneNegociacaoTeleUnderwritingDTO) {
  'use strict';

  /**
   * The APISeguradoraImplementacaoESimProdutoCloneNegociacaoNegociacaoDTO model module.
   * @module model/APISeguradoraImplementacaoESimProdutoCloneNegociacaoNegociacaoDTO
   * @version v1
   */

  /**
   * Constructs a new <code>APISeguradoraImplementacaoESimProdutoCloneNegociacaoNegociacaoDTO</code>.
   * @alias module:model/APISeguradoraImplementacaoESimProdutoCloneNegociacaoNegociacaoDTO
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>APISeguradoraImplementacaoESimProdutoCloneNegociacaoNegociacaoDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APISeguradoraImplementacaoESimProdutoCloneNegociacaoNegociacaoDTO} obj Optional instance to populate.
   * @return {module:model/APISeguradoraImplementacaoESimProdutoCloneNegociacaoNegociacaoDTO} The populated <code>APISeguradoraImplementacaoESimProdutoCloneNegociacaoNegociacaoDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('CnpjParceiro'))
        obj.cnpjParceiro = ApiClient.convertToType(data['CnpjParceiro'], 'Number');
      if (data.hasOwnProperty('Id'))
        obj.id = ApiClient.convertToType(data['Id'], 'Number');
      if (data.hasOwnProperty('Nome'))
        obj.nome = ApiClient.convertToType(data['Nome'], 'String');
      if (data.hasOwnProperty('PoliticasRelacionamento'))
        obj.politicasRelacionamento = ApiClient.convertToType(data['PoliticasRelacionamento'], [APISeguradoraImplementacaoESimProdutoCloneNegociacaoPoliticaRelacionamentoaDTO]);
      if (data.hasOwnProperty('ProdutosNegociados'))
        obj.produtosNegociados = ApiClient.convertToType(data['ProdutosNegociados'], [APISeguradoraImplementacaoESimProdutoCloneNegociacaoProdutoNegociaoDTO]);
      if (data.hasOwnProperty('TeleUnderwritings'))
        obj.teleUnderwritings = ApiClient.convertToType(data['TeleUnderwritings'], [APISeguradoraImplementacaoESimProdutoCloneNegociacaoTeleUnderwritingDTO]);
    }
    return obj;
  }

  /**
   * @member {Number} cnpjParceiro
   */
  exports.prototype.cnpjParceiro = undefined;

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} nome
   */
  exports.prototype.nome = undefined;

  /**
   * @member {Array.<module:model/APISeguradoraImplementacaoESimProdutoCloneNegociacaoPoliticaRelacionamentoaDTO>} politicasRelacionamento
   */
  exports.prototype.politicasRelacionamento = undefined;

  /**
   * @member {Array.<module:model/APISeguradoraImplementacaoESimProdutoCloneNegociacaoProdutoNegociaoDTO>} produtosNegociados
   */
  exports.prototype.produtosNegociados = undefined;

  /**
   * @member {Array.<module:model/APISeguradoraImplementacaoESimProdutoCloneNegociacaoTeleUnderwritingDTO>} teleUnderwritings
   */
  exports.prototype.teleUnderwritings = undefined;

  return exports;

}));
