/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/APISeguradoraContratoV1PropostaEndereco'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./APISeguradoraContratoV1PropostaEndereco'));
  } else {
    // Browser globals (root is window)
    if (!root.Apiseguradora) {
      root.Apiseguradora = {};
    }
    root.Apiseguradora.APISeguradoraContratoV1PropostaProfissao = factory(root.Apiseguradora.ApiClient, root.Apiseguradora.APISeguradoraContratoV1PropostaEndereco);
  }
}(this, function(ApiClient, APISeguradoraContratoV1PropostaEndereco) {
  'use strict';

  /**
   * The APISeguradoraContratoV1PropostaProfissao model module.
   * @module model/APISeguradoraContratoV1PropostaProfissao
   * @version v1
   */

  /**
   * Constructs a new <code>APISeguradoraContratoV1PropostaProfissao</code>.
   * @alias module:model/APISeguradoraContratoV1PropostaProfissao
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>APISeguradoraContratoV1PropostaProfissao</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APISeguradoraContratoV1PropostaProfissao} obj Optional instance to populate.
   * @return {module:model/APISeguradoraContratoV1PropostaProfissao} The populated <code>APISeguradoraContratoV1PropostaProfissao</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Codigo'))
        obj.codigo = ApiClient.convertToType(data['Codigo'], 'String');
      if (data.hasOwnProperty('Descricao'))
        obj.descricao = ApiClient.convertToType(data['Descricao'], 'String');
      if (data.hasOwnProperty('Categoria'))
        obj.categoria = ApiClient.convertToType(data['Categoria'], 'String');
      if (data.hasOwnProperty('NomeEmpresa'))
        obj.nomeEmpresa = ApiClient.convertToType(data['NomeEmpresa'], 'String');
      if (data.hasOwnProperty('EnderecosEmpresa'))
        obj.enderecosEmpresa = ApiClient.convertToType(data['EnderecosEmpresa'], [APISeguradoraContratoV1PropostaEndereco]);
    }
    return obj;
  }

  /**
   * @member {String} codigo
   */
  exports.prototype.codigo = undefined;

  /**
   * @member {String} descricao
   */
  exports.prototype.descricao = undefined;

  /**
   * @member {String} categoria
   */
  exports.prototype.categoria = undefined;

  /**
   * @member {String} nomeEmpresa
   */
  exports.prototype.nomeEmpresa = undefined;

  /**
   * @member {Array.<module:model/APISeguradoraContratoV1PropostaEndereco>} enderecosEmpresa
   */
  exports.prototype.enderecosEmpresa = undefined;

  return exports;

}));
