/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Apiseguradora) {
      root.Apiseguradora = {};
    }
    root.Apiseguradora.APISeguradoraContratoV1PropostaEndereco = factory(root.Apiseguradora.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The APISeguradoraContratoV1PropostaEndereco model module.
   * @module model/APISeguradoraContratoV1PropostaEndereco
   * @version v1
   */

  /**
   * Constructs a new <code>APISeguradoraContratoV1PropostaEndereco</code>.
   * @alias module:model/APISeguradoraContratoV1PropostaEndereco
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>APISeguradoraContratoV1PropostaEndereco</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APISeguradoraContratoV1PropostaEndereco} obj Optional instance to populate.
   * @return {module:model/APISeguradoraContratoV1PropostaEndereco} The populated <code>APISeguradoraContratoV1PropostaEndereco</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Tipo'))
        obj.tipo = ApiClient.convertToType(data['Tipo'], 'String');
      if (data.hasOwnProperty('Logradouro'))
        obj.logradouro = ApiClient.convertToType(data['Logradouro'], 'String');
      if (data.hasOwnProperty('Numero'))
        obj.numero = ApiClient.convertToType(data['Numero'], 'String');
      if (data.hasOwnProperty('COMPLEMENTO'))
        obj.COMPLEMENTO = ApiClient.convertToType(data['COMPLEMENTO'], Object);
      if (data.hasOwnProperty('BAIRRO'))
        obj.BAIRRO = ApiClient.convertToType(data['BAIRRO'], 'String');
      if (data.hasOwnProperty('CIDADE'))
        obj.CIDADE = ApiClient.convertToType(data['CIDADE'], 'String');
      if (data.hasOwnProperty('ESTADO'))
        obj.ESTADO = ApiClient.convertToType(data['ESTADO'], 'String');
      if (data.hasOwnProperty('CEP'))
        obj.CEP = ApiClient.convertToType(data['CEP'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} tipo
   */
  exports.prototype.tipo = undefined;

  /**
   * @member {String} logradouro
   */
  exports.prototype.logradouro = undefined;

  /**
   * @member {String} numero
   */
  exports.prototype.numero = undefined;

  /**
   * @member {Object} COMPLEMENTO
   */
  exports.prototype.COMPLEMENTO = undefined;

  /**
   * @member {String} BAIRRO
   */
  exports.prototype.BAIRRO = undefined;

  /**
   * @member {String} CIDADE
   */
  exports.prototype.CIDADE = undefined;

  /**
   * @member {String} ESTADO
   */
  exports.prototype.ESTADO = undefined;

  /**
   * @member {String} CEP
   */
  exports.prototype.CEP = undefined;

  return exports;

}));
