/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/APISeguradoraContratoV1ModeloNegocioTipoRenda'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./APISeguradoraContratoV1ModeloNegocioTipoRenda'));
  } else {
    // Browser globals (root is window)
    if (!root.Apiseguradora) {
      root.Apiseguradora = {};
    }
    root.Apiseguradora.APISeguradoraContratoV1ModeloNegocioRenda = factory(root.Apiseguradora.ApiClient, root.Apiseguradora.APISeguradoraContratoV1ModeloNegocioTipoRenda);
  }
}(this, function(ApiClient, APISeguradoraContratoV1ModeloNegocioTipoRenda) {
  'use strict';

  /**
   * The APISeguradoraContratoV1ModeloNegocioRenda model module.
   * @module model/APISeguradoraContratoV1ModeloNegocioRenda
   * @version v1
   */

  /**
   * Constructs a new <code>APISeguradoraContratoV1ModeloNegocioRenda</code>.
   * @alias module:model/APISeguradoraContratoV1ModeloNegocioRenda
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>APISeguradoraContratoV1ModeloNegocioRenda</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APISeguradoraContratoV1ModeloNegocioRenda} obj Optional instance to populate.
   * @return {module:model/APISeguradoraContratoV1ModeloNegocioRenda} The populated <code>APISeguradoraContratoV1ModeloNegocioRenda</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('tipo'))
        obj.tipo = APISeguradoraContratoV1ModeloNegocioTipoRenda.constructFromObject(data['tipo']);
      if (data.hasOwnProperty('ehPadrao'))
        obj.ehPadrao = ApiClient.convertToType(data['ehPadrao'], 'Boolean');
      if (data.hasOwnProperty('prazoInicial'))
        obj.prazoInicial = ApiClient.convertToType(data['prazoInicial'], 'Number');
      if (data.hasOwnProperty('prazoFinal'))
        obj.prazoFinal = ApiClient.convertToType(data['prazoFinal'], 'Number');
      if (data.hasOwnProperty('prazoPadrao'))
        obj.prazoPadrao = ApiClient.convertToType(data['prazoPadrao'], 'Number');
      if (data.hasOwnProperty('idadeMaioridade'))
        obj.idadeMaioridade = ApiClient.convertToType(data['idadeMaioridade'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {module:model/APISeguradoraContratoV1ModeloNegocioTipoRenda} tipo
   */
  exports.prototype.tipo = undefined;

  /**
   * @member {Boolean} ehPadrao
   */
  exports.prototype.ehPadrao = undefined;

  /**
   * @member {Number} prazoInicial
   */
  exports.prototype.prazoInicial = undefined;

  /**
   * @member {Number} prazoFinal
   */
  exports.prototype.prazoFinal = undefined;

  /**
   * @member {Number} prazoPadrao
   */
  exports.prototype.prazoPadrao = undefined;

  /**
   * @member {Number} idadeMaioridade
   */
  exports.prototype.idadeMaioridade = undefined;

  return exports;

}));
