/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Apiseguradora) {
      root.Apiseguradora = {};
    }
    root.Apiseguradora.APISeguradoraContratoV1ModeloNegocioPoliticaRelacionamento = factory(root.Apiseguradora.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The APISeguradoraContratoV1ModeloNegocioPoliticaRelacionamento model module.
   * @module model/APISeguradoraContratoV1ModeloNegocioPoliticaRelacionamento
   * @version v1
   */

  /**
   * Constructs a new <code>APISeguradoraContratoV1ModeloNegocioPoliticaRelacionamento</code>.
   * @alias module:model/APISeguradoraContratoV1ModeloNegocioPoliticaRelacionamento
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>APISeguradoraContratoV1ModeloNegocioPoliticaRelacionamento</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APISeguradoraContratoV1ModeloNegocioPoliticaRelacionamento} obj Optional instance to populate.
   * @return {module:model/APISeguradoraContratoV1ModeloNegocioPoliticaRelacionamento} The populated <code>APISeguradoraContratoV1ModeloNegocioPoliticaRelacionamento</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('modeloRelacionamento'))
        obj.modeloRelacionamento = ApiClient.convertToType(data['modeloRelacionamento'], 'Number');
      if (data.hasOwnProperty('tipoPerguntaPoliticaRelacionamento'))
        obj.tipoPerguntaPoliticaRelacionamento = ApiClient.convertToType(data['tipoPerguntaPoliticaRelacionamento'], 'String');
      if (data.hasOwnProperty('respostaPergunta'))
        obj.respostaPergunta = ApiClient.convertToType(data['respostaPergunta'], 'Boolean');
      if (data.hasOwnProperty('descricaoTipoPerguntaPoliticaRelacionamento'))
        obj.descricaoTipoPerguntaPoliticaRelacionamento = ApiClient.convertToType(data['descricaoTipoPerguntaPoliticaRelacionamento'], 'String');
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {Number} modeloRelacionamento
   */
  exports.prototype.modeloRelacionamento = undefined;

  /**
   * @member {String} tipoPerguntaPoliticaRelacionamento
   */
  exports.prototype.tipoPerguntaPoliticaRelacionamento = undefined;

  /**
   * @member {Boolean} respostaPergunta
   */
  exports.prototype.respostaPergunta = undefined;

  /**
   * @member {String} descricaoTipoPerguntaPoliticaRelacionamento
   */
  exports.prototype.descricaoTipoPerguntaPoliticaRelacionamento = undefined;

  return exports;

}));
