/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/APISeguradoraContratoV1ParImagemParceiro', 'model/APISeguradoraContratoV1ParTipoAtividadeEconomica', 'model/APISeguradoraContratoV1ParTipoParceiro'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./APISeguradoraContratoV1ParImagemParceiro'), require('./APISeguradoraContratoV1ParTipoAtividadeEconomica'), require('./APISeguradoraContratoV1ParTipoParceiro'));
  } else {
    // Browser globals (root is window)
    if (!root.Apiseguradora) {
      root.Apiseguradora = {};
    }
    root.Apiseguradora.APISeguradoraContratoV1ParDadosCadastroParceiro = factory(root.Apiseguradora.ApiClient, root.Apiseguradora.APISeguradoraContratoV1ParImagemParceiro, root.Apiseguradora.APISeguradoraContratoV1ParTipoAtividadeEconomica, root.Apiseguradora.APISeguradoraContratoV1ParTipoParceiro);
  }
}(this, function(ApiClient, APISeguradoraContratoV1ParImagemParceiro, APISeguradoraContratoV1ParTipoAtividadeEconomica, APISeguradoraContratoV1ParTipoParceiro) {
  'use strict';

  /**
   * The APISeguradoraContratoV1ParDadosCadastroParceiro model module.
   * @module model/APISeguradoraContratoV1ParDadosCadastroParceiro
   * @version v1
   */

  /**
   * Constructs a new <code>APISeguradoraContratoV1ParDadosCadastroParceiro</code>.
   * @alias module:model/APISeguradoraContratoV1ParDadosCadastroParceiro
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>APISeguradoraContratoV1ParDadosCadastroParceiro</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APISeguradoraContratoV1ParDadosCadastroParceiro} obj Optional instance to populate.
   * @return {module:model/APISeguradoraContratoV1ParDadosCadastroParceiro} The populated <code>APISeguradoraContratoV1ParDadosCadastroParceiro</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Cnpj'))
        obj.cnpj = ApiClient.convertToType(data['Cnpj'], 'String');
      if (data.hasOwnProperty('RazaoSocial'))
        obj.razaoSocial = ApiClient.convertToType(data['RazaoSocial'], 'String');
      if (data.hasOwnProperty('NomeFantasia'))
        obj.nomeFantasia = ApiClient.convertToType(data['NomeFantasia'], 'String');
      if (data.hasOwnProperty('PrioridadeAtendimentoBeneficio'))
        obj.prioridadeAtendimentoBeneficio = ApiClient.convertToType(data['PrioridadeAtendimentoBeneficio'], 'Boolean');
      if (data.hasOwnProperty('TipoAtividadeEconomica'))
        obj.tipoAtividadeEconomica = APISeguradoraContratoV1ParTipoAtividadeEconomica.constructFromObject(data['TipoAtividadeEconomica']);
      if (data.hasOwnProperty('Tipos'))
        obj.tipos = ApiClient.convertToType(data['Tipos'], [APISeguradoraContratoV1ParTipoParceiro]);
      if (data.hasOwnProperty('CorPrimaria'))
        obj.corPrimaria = ApiClient.convertToType(data['CorPrimaria'], 'String');
      if (data.hasOwnProperty('CorSecundaria'))
        obj.corSecundaria = ApiClient.convertToType(data['CorSecundaria'], 'String');
      if (data.hasOwnProperty('LogoPositivo'))
        obj.logoPositivo = APISeguradoraContratoV1ParImagemParceiro.constructFromObject(data['LogoPositivo']);
      if (data.hasOwnProperty('LogoNegativo'))
        obj.logoNegativo = APISeguradoraContratoV1ParImagemParceiro.constructFromObject(data['LogoNegativo']);
      if (data.hasOwnProperty('ImagemTopo'))
        obj.imagemTopo = APISeguradoraContratoV1ParImagemParceiro.constructFromObject(data['ImagemTopo']);
      if (data.hasOwnProperty('ImagemServico'))
        obj.imagemServico = APISeguradoraContratoV1ParImagemParceiro.constructFromObject(data['ImagemServico']);
    }
    return obj;
  }

  /**
   * @member {String} cnpj
   */
  exports.prototype.cnpj = undefined;

  /**
   * @member {String} razaoSocial
   */
  exports.prototype.razaoSocial = undefined;

  /**
   * @member {String} nomeFantasia
   */
  exports.prototype.nomeFantasia = undefined;

  /**
   * @member {Boolean} prioridadeAtendimentoBeneficio
   */
  exports.prototype.prioridadeAtendimentoBeneficio = undefined;

  /**
   * @member {module:model/APISeguradoraContratoV1ParTipoAtividadeEconomica} tipoAtividadeEconomica
   */
  exports.prototype.tipoAtividadeEconomica = undefined;

  /**
   * @member {Array.<module:model/APISeguradoraContratoV1ParTipoParceiro>} tipos
   */
  exports.prototype.tipos = undefined;

  /**
   * @member {String} corPrimaria
   */
  exports.prototype.corPrimaria = undefined;

  /**
   * @member {String} corSecundaria
   */
  exports.prototype.corSecundaria = undefined;

  /**
   * @member {module:model/APISeguradoraContratoV1ParImagemParceiro} logoPositivo
   */
  exports.prototype.logoPositivo = undefined;

  /**
   * @member {module:model/APISeguradoraContratoV1ParImagemParceiro} logoNegativo
   */
  exports.prototype.logoNegativo = undefined;

  /**
   * @member {module:model/APISeguradoraContratoV1ParImagemParceiro} imagemTopo
   */
  exports.prototype.imagemTopo = undefined;

  /**
   * @member {module:model/APISeguradoraContratoV1ParImagemParceiro} imagemServico
   */
  exports.prototype.imagemServico = undefined;

  return exports;

}));
