/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/APISeguradoraContratoV1ModeloNegocioGrupoCausaFatoGerador'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./APISeguradoraContratoV1ModeloNegocioGrupoCausaFatoGerador'));
  } else {
    // Browser globals (root is window)
    if (!root.Apiseguradora) {
      root.Apiseguradora = {};
    }
    root.Apiseguradora.APISeguradoraContratoV1ModeloNegocioSubGrupoCausaFatoGerador = factory(root.Apiseguradora.ApiClient, root.Apiseguradora.APISeguradoraContratoV1ModeloNegocioGrupoCausaFatoGerador);
  }
}(this, function(ApiClient, APISeguradoraContratoV1ModeloNegocioGrupoCausaFatoGerador) {
  'use strict';

  /**
   * The APISeguradoraContratoV1ModeloNegocioSubGrupoCausaFatoGerador model module.
   * @module model/APISeguradoraContratoV1ModeloNegocioSubGrupoCausaFatoGerador
   * @version v1
   */

  /**
   * Constructs a new <code>APISeguradoraContratoV1ModeloNegocioSubGrupoCausaFatoGerador</code>.
   * @alias module:model/APISeguradoraContratoV1ModeloNegocioSubGrupoCausaFatoGerador
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>APISeguradoraContratoV1ModeloNegocioSubGrupoCausaFatoGerador</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APISeguradoraContratoV1ModeloNegocioSubGrupoCausaFatoGerador} obj Optional instance to populate.
   * @return {module:model/APISeguradoraContratoV1ModeloNegocioSubGrupoCausaFatoGerador} The populated <code>APISeguradoraContratoV1ModeloNegocioSubGrupoCausaFatoGerador</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('primario'))
        obj.primario = APISeguradoraContratoV1ModeloNegocioGrupoCausaFatoGerador.constructFromObject(data['primario']);
      if (data.hasOwnProperty('secundario'))
        obj.secundario = APISeguradoraContratoV1ModeloNegocioGrupoCausaFatoGerador.constructFromObject(data['secundario']);
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {module:model/APISeguradoraContratoV1ModeloNegocioGrupoCausaFatoGerador} primario
   */
  exports.prototype.primario = undefined;

  /**
   * @member {module:model/APISeguradoraContratoV1ModeloNegocioGrupoCausaFatoGerador} secundario
   */
  exports.prototype.secundario = undefined;

  return exports;

}));
