/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Apiseguradora) {
      root.Apiseguradora = {};
    }
    root.Apiseguradora.APISeguradoraContratoV1PropostaDocumento = factory(root.Apiseguradora.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The APISeguradoraContratoV1PropostaDocumento model module.
   * @module model/APISeguradoraContratoV1PropostaDocumento
   * @version v1
   */

  /**
   * Constructs a new <code>APISeguradoraContratoV1PropostaDocumento</code>.
   * @alias module:model/APISeguradoraContratoV1PropostaDocumento
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>APISeguradoraContratoV1PropostaDocumento</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APISeguradoraContratoV1PropostaDocumento} obj Optional instance to populate.
   * @return {module:model/APISeguradoraContratoV1PropostaDocumento} The populated <code>APISeguradoraContratoV1PropostaDocumento</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('NaturezaDocumento'))
        obj.naturezaDocumento = ApiClient.convertToType(data['NaturezaDocumento'], 'String');
      if (data.hasOwnProperty('NumeroDocumento'))
        obj.numeroDocumento = ApiClient.convertToType(data['NumeroDocumento'], 'String');
      if (data.hasOwnProperty('OrgaoExpeditor'))
        obj.orgaoExpeditor = ApiClient.convertToType(data['OrgaoExpeditor'], 'String');
      if (data.hasOwnProperty('DataExpedicao'))
        obj.dataExpedicao = ApiClient.convertToType(data['DataExpedicao'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} naturezaDocumento
   */
  exports.prototype.naturezaDocumento = undefined;

  /**
   * @member {String} numeroDocumento
   */
  exports.prototype.numeroDocumento = undefined;

  /**
   * @member {String} orgaoExpeditor
   */
  exports.prototype.orgaoExpeditor = undefined;

  /**
   * @member {String} dataExpedicao
   */
  exports.prototype.dataExpedicao = undefined;

  return exports;

}));
