/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/APISeguradoraContratoV1ModeloNegocioLimitePorFaixaEtaria', 'model/APISeguradoraContratoV1ModeloNegocioLimitePorFaixaProfissao', 'model/APISeguradoraContratoV1ModeloNegocioLimitePorFaixaRenda'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./APISeguradoraContratoV1ModeloNegocioLimitePorFaixaEtaria'), require('./APISeguradoraContratoV1ModeloNegocioLimitePorFaixaProfissao'), require('./APISeguradoraContratoV1ModeloNegocioLimitePorFaixaRenda'));
  } else {
    // Browser globals (root is window)
    if (!root.Apiseguradora) {
      root.Apiseguradora = {};
    }
    root.Apiseguradora.APISeguradoraContratoV1ModeloNegocioLimiteOperacionalPorFaixa = factory(root.Apiseguradora.ApiClient, root.Apiseguradora.APISeguradoraContratoV1ModeloNegocioLimitePorFaixaEtaria, root.Apiseguradora.APISeguradoraContratoV1ModeloNegocioLimitePorFaixaProfissao, root.Apiseguradora.APISeguradoraContratoV1ModeloNegocioLimitePorFaixaRenda);
  }
}(this, function(ApiClient, APISeguradoraContratoV1ModeloNegocioLimitePorFaixaEtaria, APISeguradoraContratoV1ModeloNegocioLimitePorFaixaProfissao, APISeguradoraContratoV1ModeloNegocioLimitePorFaixaRenda) {
  'use strict';

  /**
   * The APISeguradoraContratoV1ModeloNegocioLimiteOperacionalPorFaixa model module.
   * @module model/APISeguradoraContratoV1ModeloNegocioLimiteOperacionalPorFaixa
   * @version v1
   */

  /**
   * Constructs a new <code>APISeguradoraContratoV1ModeloNegocioLimiteOperacionalPorFaixa</code>.
   * @alias module:model/APISeguradoraContratoV1ModeloNegocioLimiteOperacionalPorFaixa
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>APISeguradoraContratoV1ModeloNegocioLimiteOperacionalPorFaixa</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APISeguradoraContratoV1ModeloNegocioLimiteOperacionalPorFaixa} obj Optional instance to populate.
   * @return {module:model/APISeguradoraContratoV1ModeloNegocioLimiteOperacionalPorFaixa} The populated <code>APISeguradoraContratoV1ModeloNegocioLimiteOperacionalPorFaixa</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('sigla'))
        obj.sigla = ApiClient.convertToType(data['sigla'], 'String');
      if (data.hasOwnProperty('descricao'))
        obj.descricao = ApiClient.convertToType(data['descricao'], 'String');
      if (data.hasOwnProperty('nomeTipoLimiteOperacional'))
        obj.nomeTipoLimiteOperacional = ApiClient.convertToType(data['nomeTipoLimiteOperacional'], 'String');
      if (data.hasOwnProperty('tipoGrupoCobertura'))
        obj.tipoGrupoCobertura = ApiClient.convertToType(data['tipoGrupoCobertura'], 'String');
      if (data.hasOwnProperty('coberturasIds'))
        obj.coberturasIds = ApiClient.convertToType(data['coberturasIds'], ['Number']);
      if (data.hasOwnProperty('tipoLimiteOperacional'))
        obj.tipoLimiteOperacional = ApiClient.convertToType(data['tipoLimiteOperacional'], 'String');
      if (data.hasOwnProperty('limitesPorIdade'))
        obj.limitesPorIdade = ApiClient.convertToType(data['limitesPorIdade'], [APISeguradoraContratoV1ModeloNegocioLimitePorFaixaEtaria]);
      if (data.hasOwnProperty('limitesPorRenda'))
        obj.limitesPorRenda = ApiClient.convertToType(data['limitesPorRenda'], [APISeguradoraContratoV1ModeloNegocioLimitePorFaixaRenda]);
      if (data.hasOwnProperty('limitesPorProfissoes'))
        obj.limitesPorProfissoes = ApiClient.convertToType(data['limitesPorProfissoes'], [APISeguradoraContratoV1ModeloNegocioLimitePorFaixaProfissao]);
      if (data.hasOwnProperty('limiteOperacionalCausaId'))
        obj.limiteOperacionalCausaId = ApiClient.convertToType(data['limiteOperacionalCausaId'], 'Number');
    }
    return obj;
  }

  /**
   * @member {String} sigla
   */
  exports.prototype.sigla = undefined;

  /**
   * @member {String} descricao
   */
  exports.prototype.descricao = undefined;

  /**
   * @member {String} nomeTipoLimiteOperacional
   */
  exports.prototype.nomeTipoLimiteOperacional = undefined;

  /**
   * @member {String} tipoGrupoCobertura
   */
  exports.prototype.tipoGrupoCobertura = undefined;

  /**
   * @member {Array.<Number>} coberturasIds
   */
  exports.prototype.coberturasIds = undefined;

  /**
   * @member {module:model/APISeguradoraContratoV1ModeloNegocioLimiteOperacionalPorFaixa.TipoLimiteOperacionalEnum} tipoLimiteOperacional
   */
  exports.prototype.tipoLimiteOperacional = undefined;

  /**
   * @member {Array.<module:model/APISeguradoraContratoV1ModeloNegocioLimitePorFaixaEtaria>} limitesPorIdade
   */
  exports.prototype.limitesPorIdade = undefined;

  /**
   * @member {Array.<module:model/APISeguradoraContratoV1ModeloNegocioLimitePorFaixaRenda>} limitesPorRenda
   */
  exports.prototype.limitesPorRenda = undefined;

  /**
   * @member {Array.<module:model/APISeguradoraContratoV1ModeloNegocioLimitePorFaixaProfissao>} limitesPorProfissoes
   */
  exports.prototype.limitesPorProfissoes = undefined;

  /**
   * @member {Number} limiteOperacionalCausaId
   */
  exports.prototype.limiteOperacionalCausaId = undefined;


  /**
   * Allowed values for the <code>tipoLimiteOperacional</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TipoLimiteOperacionalEnum = {
    /**
     * value: "Indefinido"
     * @const
     */
    indefinido: "Indefinido",

    /**
     * value: "Idade"
     * @const
     */
    idade: "Idade",

    /**
     * value: "Profissao"
     * @const
     */
    profissao: "Profissao",

    /**
     * value: "Renda"
     * @const
     */
    renda: "Renda"
  };

  return exports;

}));
