/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/APISeguradoraContratoV1PropostaConjuge', 'model/APISeguradoraContratoV1PropostaDocumento', 'model/APISeguradoraContratoV1PropostaEndereco', 'model/APISeguradoraContratoV1PropostaParentescoCorretor', 'model/APISeguradoraContratoV1PropostaProfissao', 'model/APISeguradoraContratoV1PropostaRepresentanteLegal', 'model/APISeguradoraContratoV1PropostaTelefone'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./APISeguradoraContratoV1PropostaConjuge'), require('./APISeguradoraContratoV1PropostaDocumento'), require('./APISeguradoraContratoV1PropostaEndereco'), require('./APISeguradoraContratoV1PropostaParentescoCorretor'), require('./APISeguradoraContratoV1PropostaProfissao'), require('./APISeguradoraContratoV1PropostaRepresentanteLegal'), require('./APISeguradoraContratoV1PropostaTelefone'));
  } else {
    // Browser globals (root is window)
    if (!root.Apiseguradora) {
      root.Apiseguradora = {};
    }
    root.Apiseguradora.APISeguradoraContratoV1PropostaDadosProponente = factory(root.Apiseguradora.ApiClient, root.Apiseguradora.APISeguradoraContratoV1PropostaConjuge, root.Apiseguradora.APISeguradoraContratoV1PropostaDocumento, root.Apiseguradora.APISeguradoraContratoV1PropostaEndereco, root.Apiseguradora.APISeguradoraContratoV1PropostaParentescoCorretor, root.Apiseguradora.APISeguradoraContratoV1PropostaProfissao, root.Apiseguradora.APISeguradoraContratoV1PropostaRepresentanteLegal, root.Apiseguradora.APISeguradoraContratoV1PropostaTelefone);
  }
}(this, function(ApiClient, APISeguradoraContratoV1PropostaConjuge, APISeguradoraContratoV1PropostaDocumento, APISeguradoraContratoV1PropostaEndereco, APISeguradoraContratoV1PropostaParentescoCorretor, APISeguradoraContratoV1PropostaProfissao, APISeguradoraContratoV1PropostaRepresentanteLegal, APISeguradoraContratoV1PropostaTelefone) {
  'use strict';

  /**
   * The APISeguradoraContratoV1PropostaDadosProponente model module.
   * @module model/APISeguradoraContratoV1PropostaDadosProponente
   * @version v1
   */

  /**
   * Constructs a new <code>APISeguradoraContratoV1PropostaDadosProponente</code>.
   * @alias module:model/APISeguradoraContratoV1PropostaDadosProponente
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>APISeguradoraContratoV1PropostaDadosProponente</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APISeguradoraContratoV1PropostaDadosProponente} obj Optional instance to populate.
   * @return {module:model/APISeguradoraContratoV1PropostaDadosProponente} The populated <code>APISeguradoraContratoV1PropostaDadosProponente</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Matricula'))
        obj.matricula = ApiClient.convertToType(data['Matricula'], 'Number');
      if (data.hasOwnProperty('Nome'))
        obj.nome = ApiClient.convertToType(data['Nome'], 'String');
      if (data.hasOwnProperty('DtNascimento'))
        obj.dtNascimento = ApiClient.convertToType(data['DtNascimento'], 'Date');
      if (data.hasOwnProperty('Idade'))
        obj.idade = ApiClient.convertToType(data['Idade'], 'Number');
      if (data.hasOwnProperty('Sexo'))
        obj.sexo = ApiClient.convertToType(data['Sexo'], 'String');
      if (data.hasOwnProperty('EstadoCivil'))
        obj.estadoCivil = ApiClient.convertToType(data['EstadoCivil'], 'String');
      if (data.hasOwnProperty('CPF'))
        obj.CPF = ApiClient.convertToType(data['CPF'], 'String');
      if (data.hasOwnProperty('TitularCpf'))
        obj.titularCpf = ApiClient.convertToType(data['TitularCpf'], 'Boolean');
      if (data.hasOwnProperty('Email'))
        obj.email = ApiClient.convertToType(data['Email'], 'String');
      if (data.hasOwnProperty('ResideBrasil'))
        obj.resideBrasil = ApiClient.convertToType(data['ResideBrasil'], 'Boolean');
      if (data.hasOwnProperty('RendaMensal'))
        obj.rendaMensal = ApiClient.convertToType(data['RendaMensal'], 'Number');
      if (data.hasOwnProperty('NumFilhos'))
        obj.numFilhos = ApiClient.convertToType(data['NumFilhos'], 'Number');
      if (data.hasOwnProperty('PPE'))
        obj.PPE = ApiClient.convertToType(data['PPE'], 'Boolean');
      if (data.hasOwnProperty('Documentos'))
        obj.documentos = ApiClient.convertToType(data['Documentos'], [APISeguradoraContratoV1PropostaDocumento]);
      if (data.hasOwnProperty('TipoEnderecoCorrespondecia'))
        obj.tipoEnderecoCorrespondecia = ApiClient.convertToType(data['TipoEnderecoCorrespondecia'], 'String');
      if (data.hasOwnProperty('Enderecos'))
        obj.enderecos = ApiClient.convertToType(data['Enderecos'], [APISeguradoraContratoV1PropostaEndereco]);
      if (data.hasOwnProperty('Telefones'))
        obj.telefones = ApiClient.convertToType(data['Telefones'], [APISeguradoraContratoV1PropostaTelefone]);
      if (data.hasOwnProperty('Profissao'))
        obj.profissao = APISeguradoraContratoV1PropostaProfissao.constructFromObject(data['Profissao']);
      if (data.hasOwnProperty('Conjuge'))
        obj.conjuge = APISeguradoraContratoV1PropostaConjuge.constructFromObject(data['Conjuge']);
      if (data.hasOwnProperty('RepresentanteLegal'))
        obj.representanteLegal = APISeguradoraContratoV1PropostaRepresentanteLegal.constructFromObject(data['RepresentanteLegal']);
      if (data.hasOwnProperty('ParentescoCorretor'))
        obj.parentescoCorretor = APISeguradoraContratoV1PropostaParentescoCorretor.constructFromObject(data['ParentescoCorretor']);
    }
    return obj;
  }

  /**
   * @member {Number} matricula
   */
  exports.prototype.matricula = undefined;

  /**
   * @member {String} nome
   */
  exports.prototype.nome = undefined;

  /**
   * @member {Date} dtNascimento
   */
  exports.prototype.dtNascimento = undefined;

  /**
   * @member {Number} idade
   */
  exports.prototype.idade = undefined;

  /**
   * @member {String} sexo
   */
  exports.prototype.sexo = undefined;

  /**
   * @member {String} estadoCivil
   */
  exports.prototype.estadoCivil = undefined;

  /**
   * @member {String} CPF
   */
  exports.prototype.CPF = undefined;

  /**
   * @member {Boolean} titularCpf
   */
  exports.prototype.titularCpf = undefined;

  /**
   * @member {String} email
   */
  exports.prototype.email = undefined;

  /**
   * @member {Boolean} resideBrasil
   */
  exports.prototype.resideBrasil = undefined;

  /**
   * @member {Number} rendaMensal
   */
  exports.prototype.rendaMensal = undefined;

  /**
   * @member {Number} numFilhos
   */
  exports.prototype.numFilhos = undefined;

  /**
   * @member {Boolean} PPE
   */
  exports.prototype.PPE = undefined;

  /**
   * @member {Array.<module:model/APISeguradoraContratoV1PropostaDocumento>} documentos
   */
  exports.prototype.documentos = undefined;

  /**
   * @member {String} tipoEnderecoCorrespondecia
   */
  exports.prototype.tipoEnderecoCorrespondecia = undefined;

  /**
   * @member {Array.<module:model/APISeguradoraContratoV1PropostaEndereco>} enderecos
   */
  exports.prototype.enderecos = undefined;

  /**
   * @member {Array.<module:model/APISeguradoraContratoV1PropostaTelefone>} telefones
   */
  exports.prototype.telefones = undefined;

  /**
   * @member {module:model/APISeguradoraContratoV1PropostaProfissao} profissao
   */
  exports.prototype.profissao = undefined;

  /**
   * @member {module:model/APISeguradoraContratoV1PropostaConjuge} conjuge
   */
  exports.prototype.conjuge = undefined;

  /**
   * @member {module:model/APISeguradoraContratoV1PropostaRepresentanteLegal} representanteLegal
   */
  exports.prototype.representanteLegal = undefined;

  /**
   * @member {module:model/APISeguradoraContratoV1PropostaParentescoCorretor} parentescoCorretor
   */
  exports.prototype.parentescoCorretor = undefined;

  return exports;

}));
