/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Apiseguradora) {
      root.Apiseguradora = {};
    }
    root.Apiseguradora.APISeguradoraImplementacaoComissoesCondicaoComercialFaixaPercentual = factory(root.Apiseguradora.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The APISeguradoraImplementacaoComissoesCondicaoComercialFaixaPercentual model module.
   * @module model/APISeguradoraImplementacaoComissoesCondicaoComercialFaixaPercentual
   * @version v1
   */

  /**
   * Constructs a new <code>APISeguradoraImplementacaoComissoesCondicaoComercialFaixaPercentual</code>.
   * @alias module:model/APISeguradoraImplementacaoComissoesCondicaoComercialFaixaPercentual
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>APISeguradoraImplementacaoComissoesCondicaoComercialFaixaPercentual</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APISeguradoraImplementacaoComissoesCondicaoComercialFaixaPercentual} obj Optional instance to populate.
   * @return {module:model/APISeguradoraImplementacaoComissoesCondicaoComercialFaixaPercentual} The populated <code>APISeguradoraImplementacaoComissoesCondicaoComercialFaixaPercentual</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('TipoAngariacao'))
        obj.tipoAngariacao = ApiClient.convertToType(data['TipoAngariacao'], 'String');
      if (data.hasOwnProperty('TipoFatoGeradorComissao'))
        obj.tipoFatoGeradorComissao = ApiClient.convertToType(data['TipoFatoGeradorComissao'], 'String');
      if (data.hasOwnProperty('TipoFaixaPercentual'))
        obj.tipoFaixaPercentual = ApiClient.convertToType(data['TipoFaixaPercentual'], 'String');
      if (data.hasOwnProperty('ValorInicial'))
        obj.valorInicial = ApiClient.convertToType(data['ValorInicial'], 'Number');
      if (data.hasOwnProperty('ValorFinal'))
        obj.valorFinal = ApiClient.convertToType(data['ValorFinal'], 'Number');
      if (data.hasOwnProperty('Percentual'))
        obj.percentual = ApiClient.convertToType(data['Percentual'], 'Number');
      if (data.hasOwnProperty('Periodicidade'))
        obj.periodicidade = ApiClient.convertToType(data['Periodicidade'], 'Number');
      if (data.hasOwnProperty('ValorMinimo'))
        obj.valorMinimo = ApiClient.convertToType(data['ValorMinimo'], 'Number');
    }
    return obj;
  }

  /**
   * @member {String} tipoAngariacao
   */
  exports.prototype.tipoAngariacao = undefined;

  /**
   * @member {String} tipoFatoGeradorComissao
   */
  exports.prototype.tipoFatoGeradorComissao = undefined;

  /**
   * @member {String} tipoFaixaPercentual
   */
  exports.prototype.tipoFaixaPercentual = undefined;

  /**
   * @member {Number} valorInicial
   */
  exports.prototype.valorInicial = undefined;

  /**
   * @member {Number} valorFinal
   */
  exports.prototype.valorFinal = undefined;

  /**
   * @member {Number} percentual
   */
  exports.prototype.percentual = undefined;

  /**
   * @member {Number} periodicidade
   */
  exports.prototype.periodicidade = undefined;

  /**
   * @member {Number} valorMinimo
   */
  exports.prototype.valorMinimo = undefined;

  return exports;

}));
