/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/APISeguradoraContratoV1PropostaAgendamentoMedico', 'model/APISeguradoraContratoV1PropostaHierarquia', 'model/APISeguradoraContratoV1PropostaProponente'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./APISeguradoraContratoV1PropostaAgendamentoMedico'), require('./APISeguradoraContratoV1PropostaHierarquia'), require('./APISeguradoraContratoV1PropostaProponente'));
  } else {
    // Browser globals (root is window)
    if (!root.Apiseguradora) {
      root.Apiseguradora = {};
    }
    root.Apiseguradora.APISeguradoraContratoV1PropostaResumoDaProposta = factory(root.Apiseguradora.ApiClient, root.Apiseguradora.APISeguradoraContratoV1PropostaAgendamentoMedico, root.Apiseguradora.APISeguradoraContratoV1PropostaHierarquia, root.Apiseguradora.APISeguradoraContratoV1PropostaProponente);
  }
}(this, function(ApiClient, APISeguradoraContratoV1PropostaAgendamentoMedico, APISeguradoraContratoV1PropostaHierarquia, APISeguradoraContratoV1PropostaProponente) {
  'use strict';

  /**
   * The APISeguradoraContratoV1PropostaResumoDaProposta model module.
   * @module model/APISeguradoraContratoV1PropostaResumoDaProposta
   * @version v1
   */

  /**
   * Constructs a new <code>APISeguradoraContratoV1PropostaResumoDaProposta</code>.
   * @alias module:model/APISeguradoraContratoV1PropostaResumoDaProposta
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>APISeguradoraContratoV1PropostaResumoDaProposta</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APISeguradoraContratoV1PropostaResumoDaProposta} obj Optional instance to populate.
   * @return {module:model/APISeguradoraContratoV1PropostaResumoDaProposta} The populated <code>APISeguradoraContratoV1PropostaResumoDaProposta</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('dataProtocolo'))
        obj.dataProtocolo = ApiClient.convertToType(data['dataProtocolo'], 'String');
      if (data.hasOwnProperty('modeloProposta'))
        obj.modeloProposta = ApiClient.convertToType(data['modeloProposta'], 'String');
      if (data.hasOwnProperty('valorProposta'))
        obj.valorProposta = ApiClient.convertToType(data['valorProposta'], 'String');
      if (data.hasOwnProperty('formaPagamento'))
        obj.formaPagamento = ApiClient.convertToType(data['formaPagamento'], 'String');
      if (data.hasOwnProperty('periodicidadeCobranca'))
        obj.periodicidadeCobranca = ApiClient.convertToType(data['periodicidadeCobranca'], 'String');
      if (data.hasOwnProperty('hierarquia'))
        obj.hierarquia = APISeguradoraContratoV1PropostaHierarquia.constructFromObject(data['hierarquia']);
      if (data.hasOwnProperty('proponente'))
        obj.proponente = APISeguradoraContratoV1PropostaProponente.constructFromObject(data['proponente']);
      if (data.hasOwnProperty('agendamentosmedicos'))
        obj.agendamentosmedicos = APISeguradoraContratoV1PropostaAgendamentoMedico.constructFromObject(data['agendamentosmedicos']);
      if (data.hasOwnProperty('mensagens'))
        obj.mensagens = ApiClient.convertToType(data['mensagens'], ['String']);
    }
    return obj;
  }

  /**
   * @member {String} dataProtocolo
   */
  exports.prototype.dataProtocolo = undefined;

  /**
   * @member {String} modeloProposta
   */
  exports.prototype.modeloProposta = undefined;

  /**
   * @member {String} valorProposta
   */
  exports.prototype.valorProposta = undefined;

  /**
   * @member {String} formaPagamento
   */
  exports.prototype.formaPagamento = undefined;

  /**
   * @member {String} periodicidadeCobranca
   */
  exports.prototype.periodicidadeCobranca = undefined;

  /**
   * @member {module:model/APISeguradoraContratoV1PropostaHierarquia} hierarquia
   */
  exports.prototype.hierarquia = undefined;

  /**
   * @member {module:model/APISeguradoraContratoV1PropostaProponente} proponente
   */
  exports.prototype.proponente = undefined;

  /**
   * @member {module:model/APISeguradoraContratoV1PropostaAgendamentoMedico} agendamentosmedicos
   */
  exports.prototype.agendamentosmedicos = undefined;

  /**
   * @member {Array.<String>} mensagens
   */
  exports.prototype.mensagens = undefined;

  return exports;

}));
