/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/APISeguradoraContratoV1CapitalSeguradoAcumuladoCapitalSeguradoAcumuladoPesquisa', 'model/APISeguradoraHelperResultadoDaOperacaoRestAPISeguradoraContratoV1CapitalSeguradoAcumuladoResultadoCapitalSeguradoAcumulado'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/APISeguradoraContratoV1CapitalSeguradoAcumuladoCapitalSeguradoAcumuladoPesquisa'), require('../model/APISeguradoraHelperResultadoDaOperacaoRestAPISeguradoraContratoV1CapitalSeguradoAcumuladoResultadoCapitalSeguradoAcumulado'));
  } else {
    // Browser globals (root is window)
    if (!root.Apiseguradora) {
      root.Apiseguradora = {};
    }
    root.Apiseguradora.CapitalSeguradoAcumuladoApi = factory(root.Apiseguradora.ApiClient, root.Apiseguradora.APISeguradoraContratoV1CapitalSeguradoAcumuladoCapitalSeguradoAcumuladoPesquisa, root.Apiseguradora.APISeguradoraHelperResultadoDaOperacaoRestAPISeguradoraContratoV1CapitalSeguradoAcumuladoResultadoCapitalSeguradoAcumulado);
  }
}(this, function(ApiClient, APISeguradoraContratoV1CapitalSeguradoAcumuladoCapitalSeguradoAcumuladoPesquisa, APISeguradoraHelperResultadoDaOperacaoRestAPISeguradoraContratoV1CapitalSeguradoAcumuladoResultadoCapitalSeguradoAcumulado) {
  'use strict';

  /**
   * CapitalSeguradoAcumulado service.
   * @module api/CapitalSeguradoAcumuladoApi
   * @version v1
   */

  /**
   * Constructs a new CapitalSeguradoAcumuladoApi. 
   * @alias module:api/CapitalSeguradoAcumuladoApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the apiversionCapitalSeguradoAcumuladocnpjcnpjcodigoModeloPropostacodigoModeloPropostaPOST operation.
     * @callback module:api/CapitalSeguradoAcumuladoApi~apiversionCapitalSeguradoAcumuladocnpjcnpjcodigoModeloPropostacodigoModeloPropostaPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/APISeguradoraHelperResultadoDaOperacaoRestAPISeguradoraContratoV1CapitalSeguradoAcumuladoResultadoCapitalSeguradoAcumulado} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retorna o capital segurado acumulado do proponente por causa
     * @param {module:model/APISeguradoraContratoV1CapitalSeguradoAcumuladoCapitalSeguradoAcumuladoPesquisa} pesquisa 
     * @param {String} cnpj CNPJ do parceiro.
     * @param {String} codigoModeloProposta Código do modelo da proposta.
     * @param {String} version 
     * @param {String} authorization Token de autorização
     * @param {module:api/CapitalSeguradoAcumuladoApi~apiversionCapitalSeguradoAcumuladocnpjcnpjcodigoModeloPropostacodigoModeloPropostaPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/APISeguradoraHelperResultadoDaOperacaoRestAPISeguradoraContratoV1CapitalSeguradoAcumuladoResultadoCapitalSeguradoAcumulado}
     */
    this.apiversionCapitalSeguradoAcumuladocnpjcnpjcodigoModeloPropostacodigoModeloPropostaPOST = function(pesquisa, cnpj, codigoModeloProposta, version, authorization, callback) {
      var postBody = pesquisa;

      // verify the required parameter 'pesquisa' is set
      if (pesquisa === undefined || pesquisa === null) {
        throw new Error("Missing the required parameter 'pesquisa' when calling apiversionCapitalSeguradoAcumuladocnpjcnpjcodigoModeloPropostacodigoModeloPropostaPOST");
      }

      // verify the required parameter 'cnpj' is set
      if (cnpj === undefined || cnpj === null) {
        throw new Error("Missing the required parameter 'cnpj' when calling apiversionCapitalSeguradoAcumuladocnpjcnpjcodigoModeloPropostacodigoModeloPropostaPOST");
      }

      // verify the required parameter 'codigoModeloProposta' is set
      if (codigoModeloProposta === undefined || codigoModeloProposta === null) {
        throw new Error("Missing the required parameter 'codigoModeloProposta' when calling apiversionCapitalSeguradoAcumuladocnpjcnpjcodigoModeloPropostacodigoModeloPropostaPOST");
      }

      // verify the required parameter 'version' is set
      if (version === undefined || version === null) {
        throw new Error("Missing the required parameter 'version' when calling apiversionCapitalSeguradoAcumuladocnpjcnpjcodigoModeloPropostacodigoModeloPropostaPOST");
      }

      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling apiversionCapitalSeguradoAcumuladocnpjcnpjcodigoModeloPropostacodigoModeloPropostaPOST");
      }


      var pathParams = {
        'version': version
      };
      var queryParams = {
        'cnpj': cnpj,
        'codigoModeloProposta': codigoModeloProposta,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'authorization': authorization
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json', 'text/json', 'text/html', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded'];
      var accepts = ['application/json', 'text/json', 'text/html', 'application/xml', 'text/xml'];
      var returnType = APISeguradoraHelperResultadoDaOperacaoRestAPISeguradoraContratoV1CapitalSeguradoAcumuladoResultadoCapitalSeguradoAcumulado;

      return this.apiClient.callApi(
        '/api/{version}/CapitalSeguradoAcumulado', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
