/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/APISeguradoraContratoV1PendenciaPendencia', 'model/APISeguradoraHelperResultadoDaOperacaoRestAPISeguradoraContratoV1PendenciaPendencia', 'model/APISeguradoraHelperResultadoDaOperacaoRestSystemLinqIQueryableAPISeguradoraContratoV1PendenciaPendencia'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/APISeguradoraContratoV1PendenciaPendencia'), require('../model/APISeguradoraHelperResultadoDaOperacaoRestAPISeguradoraContratoV1PendenciaPendencia'), require('../model/APISeguradoraHelperResultadoDaOperacaoRestSystemLinqIQueryableAPISeguradoraContratoV1PendenciaPendencia'));
  } else {
    // Browser globals (root is window)
    if (!root.Apiseguradora) {
      root.Apiseguradora = {};
    }
    root.Apiseguradora.PendenciaApi = factory(root.Apiseguradora.ApiClient, root.Apiseguradora.APISeguradoraContratoV1PendenciaPendencia, root.Apiseguradora.APISeguradoraHelperResultadoDaOperacaoRestAPISeguradoraContratoV1PendenciaPendencia, root.Apiseguradora.APISeguradoraHelperResultadoDaOperacaoRestSystemLinqIQueryableAPISeguradoraContratoV1PendenciaPendencia);
  }
}(this, function(ApiClient, APISeguradoraContratoV1PendenciaPendencia, APISeguradoraHelperResultadoDaOperacaoRestAPISeguradoraContratoV1PendenciaPendencia, APISeguradoraHelperResultadoDaOperacaoRestSystemLinqIQueryableAPISeguradoraContratoV1PendenciaPendencia) {
  'use strict';

  /**
   * Pendencia service.
   * @module api/PendenciaApi
   * @version v1
   */

  /**
   * Constructs a new PendenciaApi. 
   * @alias module:api/PendenciaApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the apiversionpendenciacnpjcnpjPUT operation.
     * @callback module:api/PendenciaApi~apiversionpendenciacnpjcnpjPUTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/APISeguradoraHelperResultadoDaOperacaoRestAPISeguradoraContratoV1PendenciaPendencia} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Responde uma pendência.
     * Responde uma pendência.
     * @param {module:model/APISeguradoraContratoV1PendenciaPendencia} pendencia Informações da resposta da pendência.
     * @param {String} cnpj CNPJ do parceiro
     * @param {String} version 
     * @param {String} authorization Token de autorização
     * @param {module:api/PendenciaApi~apiversionpendenciacnpjcnpjPUTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/APISeguradoraHelperResultadoDaOperacaoRestAPISeguradoraContratoV1PendenciaPendencia}
     */
    this.apiversionpendenciacnpjcnpjPUT = function(pendencia, cnpj, version, authorization, callback) {
      var postBody = pendencia;

      // verify the required parameter 'pendencia' is set
      if (pendencia === undefined || pendencia === null) {
        throw new Error("Missing the required parameter 'pendencia' when calling apiversionpendenciacnpjcnpjPUT");
      }

      // verify the required parameter 'cnpj' is set
      if (cnpj === undefined || cnpj === null) {
        throw new Error("Missing the required parameter 'cnpj' when calling apiversionpendenciacnpjcnpjPUT");
      }

      // verify the required parameter 'version' is set
      if (version === undefined || version === null) {
        throw new Error("Missing the required parameter 'version' when calling apiversionpendenciacnpjcnpjPUT");
      }

      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling apiversionpendenciacnpjcnpjPUT");
      }


      var pathParams = {
        'version': version
      };
      var queryParams = {
        'cnpj': cnpj,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'authorization': authorization
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json', 'text/json', 'text/html', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded'];
      var accepts = ['application/json', 'text/json', 'text/html', 'application/xml', 'text/xml'];
      var returnType = APISeguradoraHelperResultadoDaOperacaoRestAPISeguradoraContratoV1PendenciaPendencia;

      return this.apiClient.callApi(
        '/api/{version}/Pendencia', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the apiversionpendenciacnpjcnpjnumeroPropostanumeroPropostaGET operation.
     * @callback module:api/PendenciaApi~apiversionpendenciacnpjcnpjnumeroPropostanumeroPropostaGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/APISeguradoraHelperResultadoDaOperacaoRestSystemLinqIQueryableAPISeguradoraContratoV1PendenciaPendencia} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Recupera pendências.
     * Retorna as pendências abertas para o usuário selecionado. Opcional informar o número da proposta, para receber apenas as pendências da proposta informada.
     * @param {String} cnpj CNPJ do parceiro.
     * @param {Number} numeroProposta Número da Proposta que se deseja verificar as pendências.
     * @param {String} version 
     * @param {String} authorization Token de autorização
     * @param {module:api/PendenciaApi~apiversionpendenciacnpjcnpjnumeroPropostanumeroPropostaGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/APISeguradoraHelperResultadoDaOperacaoRestSystemLinqIQueryableAPISeguradoraContratoV1PendenciaPendencia}
     */
    this.apiversionpendenciacnpjcnpjnumeroPropostanumeroPropostaGET = function(cnpj, numeroProposta, version, authorization, callback) {
      var postBody = null;

      // verify the required parameter 'cnpj' is set
      if (cnpj === undefined || cnpj === null) {
        throw new Error("Missing the required parameter 'cnpj' when calling apiversionpendenciacnpjcnpjnumeroPropostanumeroPropostaGET");
      }

      // verify the required parameter 'numeroProposta' is set
      if (numeroProposta === undefined || numeroProposta === null) {
        throw new Error("Missing the required parameter 'numeroProposta' when calling apiversionpendenciacnpjcnpjnumeroPropostanumeroPropostaGET");
      }

      // verify the required parameter 'version' is set
      if (version === undefined || version === null) {
        throw new Error("Missing the required parameter 'version' when calling apiversionpendenciacnpjcnpjnumeroPropostanumeroPropostaGET");
      }

      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling apiversionpendenciacnpjcnpjnumeroPropostanumeroPropostaGET");
      }


      var pathParams = {
        'version': version
      };
      var queryParams = {
        'cnpj': cnpj,
        'numeroProposta': numeroProposta,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'authorization': authorization
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json', 'text/json', 'text/html', 'application/xml', 'text/xml'];
      var returnType = APISeguradoraHelperResultadoDaOperacaoRestSystemLinqIQueryableAPISeguradoraContratoV1PendenciaPendencia;

      return this.apiClient.callApi(
        '/api/{version}/Pendencia', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
