/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/APISeguradoraHelperResultadoDaOperacaoRestAPISeguradoraContratoV1ProdutoProduto', 'model/APISeguradoraHelperResultadoDaOperacaoRestSystemLinqIQueryableAPISeguradoraContratoV1ProdutoProduto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/APISeguradoraHelperResultadoDaOperacaoRestAPISeguradoraContratoV1ProdutoProduto'), require('../model/APISeguradoraHelperResultadoDaOperacaoRestSystemLinqIQueryableAPISeguradoraContratoV1ProdutoProduto'));
  } else {
    // Browser globals (root is window)
    if (!root.Apiseguradora) {
      root.Apiseguradora = {};
    }
    root.Apiseguradora.ProdutoApi = factory(root.Apiseguradora.ApiClient, root.Apiseguradora.APISeguradoraHelperResultadoDaOperacaoRestAPISeguradoraContratoV1ProdutoProduto, root.Apiseguradora.APISeguradoraHelperResultadoDaOperacaoRestSystemLinqIQueryableAPISeguradoraContratoV1ProdutoProduto);
  }
}(this, function(ApiClient, APISeguradoraHelperResultadoDaOperacaoRestAPISeguradoraContratoV1ProdutoProduto, APISeguradoraHelperResultadoDaOperacaoRestSystemLinqIQueryableAPISeguradoraContratoV1ProdutoProduto) {
  'use strict';

  /**
   * Produto service.
   * @module api/ProdutoApi
   * @version v1
   */

  /**
   * Constructs a new ProdutoApi. 
   * @alias module:api/ProdutoApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the apiversionprodutocodigoModeloPropostacodigoModeloPropostaGET operation.
     * @callback module:api/ProdutoApi~apiversionprodutocodigoModeloPropostacodigoModeloPropostaGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/APISeguradoraHelperResultadoDaOperacaoRestSystemLinqIQueryableAPISeguradoraContratoV1ProdutoProduto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Recupera produtos
     * Retorna os Produtos disponíveis para um determinado modelo de proposta
     * @param {String} codigoModeloProposta Código do modelo de proposta
     * @param {String} version 
     * @param {String} authorization Token de autorização
     * @param {module:api/ProdutoApi~apiversionprodutocodigoModeloPropostacodigoModeloPropostaGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/APISeguradoraHelperResultadoDaOperacaoRestSystemLinqIQueryableAPISeguradoraContratoV1ProdutoProduto}
     */
    this.apiversionprodutocodigoModeloPropostacodigoModeloPropostaGET = function(codigoModeloProposta, version, authorization, callback) {
      var postBody = null;

      // verify the required parameter 'codigoModeloProposta' is set
      if (codigoModeloProposta === undefined || codigoModeloProposta === null) {
        throw new Error("Missing the required parameter 'codigoModeloProposta' when calling apiversionprodutocodigoModeloPropostacodigoModeloPropostaGET");
      }

      // verify the required parameter 'version' is set
      if (version === undefined || version === null) {
        throw new Error("Missing the required parameter 'version' when calling apiversionprodutocodigoModeloPropostacodigoModeloPropostaGET");
      }

      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling apiversionprodutocodigoModeloPropostacodigoModeloPropostaGET");
      }


      var pathParams = {
        'version': version
      };
      var queryParams = {
        'codigoModeloProposta': codigoModeloProposta,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'authorization': authorization
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json', 'text/json', 'text/html', 'application/xml', 'text/xml'];
      var returnType = APISeguradoraHelperResultadoDaOperacaoRestSystemLinqIQueryableAPISeguradoraContratoV1ProdutoProduto;

      return this.apiClient.callApi(
        '/api/{version}/Produto', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the apiversionprodutoidcodigoModeloPropostacodigoModeloPropostaGET operation.
     * @callback module:api/ProdutoApi~apiversionprodutoidcodigoModeloPropostacodigoModeloPropostaGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/APISeguradoraHelperResultadoDaOperacaoRestAPISeguradoraContratoV1ProdutoProduto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Recupera um produto específico
     * Retorna um produto específico de um modelo de proposta
     * @param {String} codigoModeloProposta Código do modelo de proposta
     * @param {Number} id Identificador do produto
     * @param {String} version 
     * @param {String} authorization Token de autorização
     * @param {module:api/ProdutoApi~apiversionprodutoidcodigoModeloPropostacodigoModeloPropostaGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/APISeguradoraHelperResultadoDaOperacaoRestAPISeguradoraContratoV1ProdutoProduto}
     */
    this.apiversionprodutoidcodigoModeloPropostacodigoModeloPropostaGET = function(codigoModeloProposta, id, version, authorization, callback) {
      var postBody = null;

      // verify the required parameter 'codigoModeloProposta' is set
      if (codigoModeloProposta === undefined || codigoModeloProposta === null) {
        throw new Error("Missing the required parameter 'codigoModeloProposta' when calling apiversionprodutoidcodigoModeloPropostacodigoModeloPropostaGET");
      }

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling apiversionprodutoidcodigoModeloPropostacodigoModeloPropostaGET");
      }

      // verify the required parameter 'version' is set
      if (version === undefined || version === null) {
        throw new Error("Missing the required parameter 'version' when calling apiversionprodutoidcodigoModeloPropostacodigoModeloPropostaGET");
      }

      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling apiversionprodutoidcodigoModeloPropostacodigoModeloPropostaGET");
      }


      var pathParams = {
        'id': id,
        'version': version
      };
      var queryParams = {
        'codigoModeloProposta': codigoModeloProposta,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'authorization': authorization
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json', 'text/json', 'text/html', 'application/xml', 'text/xml'];
      var returnType = APISeguradoraHelperResultadoDaOperacaoRestAPISeguradoraContratoV1ProdutoProduto;

      return this.apiClient.callApi(
        '/api/{version}/Produto/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
