/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apiseguradora);
  }
}(this, function(expect, Apiseguradora) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('APISeguradoraContratoV1ModeloNegocioTeleUnderWriting', function() {
      beforeEach(function() {
        instance = new Apiseguradora.APISeguradoraContratoV1ModeloNegocioTeleUnderWriting();
      });

      it('should create an instance of APISeguradoraContratoV1ModeloNegocioTeleUnderWriting', function() {
        // TODO: update the code to test APISeguradoraContratoV1ModeloNegocioTeleUnderWriting
        expect(instance).to.be.a(Apiseguradora.APISeguradoraContratoV1ModeloNegocioTeleUnderWriting);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property empresaTeleUnderWriting (base name: "empresaTeleUnderWriting")', function() {
        // TODO: update the code to test the property empresaTeleUnderWriting
        expect(instance).to.have.property('empresaTeleUnderWriting');
        // expect(instance.empresaTeleUnderWriting).to.be(expectedValueLiteral);
      });

      it('should have the property dataInicioVigencia (base name: "dataInicioVigencia")', function() {
        // TODO: update the code to test the property dataInicioVigencia
        expect(instance).to.have.property('dataInicioVigencia');
        // expect(instance.dataInicioVigencia).to.be(expectedValueLiteral);
      });

      it('should have the property dataFimVigencia (base name: "dataFimVigencia")', function() {
        // TODO: update the code to test the property dataFimVigencia
        expect(instance).to.have.property('dataFimVigencia');
        // expect(instance.dataFimVigencia).to.be(expectedValueLiteral);
      });

      it('should have the property capitalMinimo (base name: "capitalMinimo")', function() {
        // TODO: update the code to test the property capitalMinimo
        expect(instance).to.have.property('capitalMinimo');
        // expect(instance.capitalMinimo).to.be(expectedValueLiteral);
      });

      it('should have the property capitalMaximo (base name: "capitalMaximo")', function() {
        // TODO: update the code to test the property capitalMaximo
        expect(instance).to.have.property('capitalMaximo');
        // expect(instance.capitalMaximo).to.be(expectedValueLiteral);
      });

    });
  });

}));
