/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apiseguradora);
  }
}(this, function(expect, Apiseguradora) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('APISeguradoraContratoV1PropostaProfissao', function() {
      beforeEach(function() {
        instance = new Apiseguradora.APISeguradoraContratoV1PropostaProfissao();
      });

      it('should create an instance of APISeguradoraContratoV1PropostaProfissao', function() {
        // TODO: update the code to test APISeguradoraContratoV1PropostaProfissao
        expect(instance).to.be.a(Apiseguradora.APISeguradoraContratoV1PropostaProfissao);
      });

      it('should have the property codigo (base name: "Codigo")', function() {
        // TODO: update the code to test the property codigo
        expect(instance).to.have.property('codigo');
        // expect(instance.codigo).to.be(expectedValueLiteral);
      });

      it('should have the property descricao (base name: "Descricao")', function() {
        // TODO: update the code to test the property descricao
        expect(instance).to.have.property('descricao');
        // expect(instance.descricao).to.be(expectedValueLiteral);
      });

      it('should have the property categoria (base name: "Categoria")', function() {
        // TODO: update the code to test the property categoria
        expect(instance).to.have.property('categoria');
        // expect(instance.categoria).to.be(expectedValueLiteral);
      });

      it('should have the property nomeEmpresa (base name: "NomeEmpresa")', function() {
        // TODO: update the code to test the property nomeEmpresa
        expect(instance).to.have.property('nomeEmpresa');
        // expect(instance.nomeEmpresa).to.be(expectedValueLiteral);
      });

      it('should have the property enderecosEmpresa (base name: "EnderecosEmpresa")', function() {
        // TODO: update the code to test the property enderecosEmpresa
        expect(instance).to.have.property('enderecosEmpresa');
        // expect(instance.enderecosEmpresa).to.be(expectedValueLiteral);
      });

    });
  });

}));
