/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apiseguradora);
  }
}(this, function(expect, Apiseguradora) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('APISeguradoraImplementacaoESimProdutoCloneNegociacaoModeloPropostaDTO', function() {
      beforeEach(function() {
        instance = new Apiseguradora.APISeguradoraImplementacaoESimProdutoCloneNegociacaoModeloPropostaDTO();
      });

      it('should create an instance of APISeguradoraImplementacaoESimProdutoCloneNegociacaoModeloPropostaDTO', function() {
        // TODO: update the code to test APISeguradoraImplementacaoESimProdutoCloneNegociacaoModeloPropostaDTO
        expect(instance).to.be.a(Apiseguradora.APISeguradoraImplementacaoESimProdutoCloneNegociacaoModeloPropostaDTO);
      });

      it('should have the property canalComercializacao (base name: "CanalComercializacao")', function() {
        // TODO: update the code to test the property canalComercializacao
        expect(instance).to.have.property('canalComercializacao');
        // expect(instance.canalComercializacao).to.be(expectedValueLiteral);
      });

      it('should have the property codigoModelo (base name: "CodigoModelo")', function() {
        // TODO: update the code to test the property codigoModelo
        expect(instance).to.have.property('codigoModelo');
        // expect(instance.codigoModelo).to.be(expectedValueLiteral);
      });

      it('should have the property condicaoComercialId (base name: "CondicaoComercialId")', function() {
        // TODO: update the code to test the property condicaoComercialId
        expect(instance).to.have.property('condicaoComercialId');
        // expect(instance.condicaoComercialId).to.be(expectedValueLiteral);
      });

      it('should have the property descricao (base name: "Descricao")', function() {
        // TODO: update the code to test the property descricao
        expect(instance).to.have.property('descricao');
        // expect(instance.descricao).to.be(expectedValueLiteral);
      });

      it('should have the property formaComercializacaoId (base name: "FormaComercializacaoId")', function() {
        // TODO: update the code to test the property formaComercializacaoId
        expect(instance).to.have.property('formaComercializacaoId');
        // expect(instance.formaComercializacaoId).to.be(expectedValueLiteral);
      });

      it('should have the property negociacao (base name: "Negociacao")', function() {
        // TODO: update the code to test the property negociacao
        expect(instance).to.have.property('negociacao');
        // expect(instance.negociacao).to.be(expectedValueLiteral);
      });

      it('should have the property possuiDps (base name: "PossuiDps")', function() {
        // TODO: update the code to test the property possuiDps
        expect(instance).to.have.property('possuiDps');
        // expect(instance.possuiDps).to.be(expectedValueLiteral);
      });

      it('should have the property produtosRestritos (base name: "ProdutosRestritos")', function() {
        // TODO: update the code to test the property produtosRestritos
        expect(instance).to.have.property('produtosRestritos');
        // expect(instance.produtosRestritos).to.be(expectedValueLiteral);
      });

    });
  });

}));
