/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apiseguradora);
  }
}(this, function(expect, Apiseguradora) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('APISeguradoraContratoV1PropostaProdutor', function() {
      beforeEach(function() {
        instance = new Apiseguradora.APISeguradoraContratoV1PropostaProdutor();
      });

      it('should create an instance of APISeguradoraContratoV1PropostaProdutor', function() {
        // TODO: update the code to test APISeguradoraContratoV1PropostaProdutor
        expect(instance).to.be.a(Apiseguradora.APISeguradoraContratoV1PropostaProdutor);
      });

      it('should have the property codigoProdutor (base name: "codigoProdutor")', function() {
        // TODO: update the code to test the property codigoProdutor
        expect(instance).to.have.property('codigoProdutor');
        // expect(instance.codigoProdutor).to.be(expectedValueLiteral);
      });

      it('should have the property documento (base name: "documento")', function() {
        // TODO: update the code to test the property documento
        expect(instance).to.have.property('documento');
        // expect(instance.documento).to.be(expectedValueLiteral);
      });

      it('should have the property nome (base name: "nome")', function() {
        // TODO: update the code to test the property nome
        expect(instance).to.have.property('nome');
        // expect(instance.nome).to.be(expectedValueLiteral);
      });

      it('should have the property cargo (base name: "cargo")', function() {
        // TODO: update the code to test the property cargo
        expect(instance).to.have.property('cargo');
        // expect(instance.cargo).to.be(expectedValueLiteral);
      });

      it('should have the property codigoUnidadeProducao (base name: "CodigoUnidadeProducao")', function() {
        // TODO: update the code to test the property codigoUnidadeProducao
        expect(instance).to.have.property('codigoUnidadeProducao');
        // expect(instance.codigoUnidadeProducao).to.be(expectedValueLiteral);
      });

      it('should have the property ordemHierarquia (base name: "OrdemHierarquia")', function() {
        // TODO: update the code to test the property ordemHierarquia
        expect(instance).to.have.property('ordemHierarquia');
        // expect(instance.ordemHierarquia).to.be(expectedValueLiteral);
      });

      it('should have the property numeroSusep (base name: "NumeroSusep")', function() {
        // TODO: update the code to test the property numeroSusep
        expect(instance).to.have.property('numeroSusep');
        // expect(instance.numeroSusep).to.be(expectedValueLiteral);
      });

    });
  });

}));
