/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apiseguradora);
  }
}(this, function(expect, Apiseguradora) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('APISeguradoraImplementacaoServicoServicoRegraComissaoComissionamento', function() {
      beforeEach(function() {
        instance = new Apiseguradora.APISeguradoraImplementacaoServicoServicoRegraComissaoComissionamento();
      });

      it('should create an instance of APISeguradoraImplementacaoServicoServicoRegraComissaoComissionamento', function() {
        // TODO: update the code to test APISeguradoraImplementacaoServicoServicoRegraComissaoComissionamento
        expect(instance).to.be.a(Apiseguradora.APISeguradoraImplementacaoServicoServicoRegraComissaoComissionamento);
      });

      it('should have the property tipoComissionamento (base name: "TipoComissionamento")', function() {
        // TODO: update the code to test the property tipoComissionamento
        expect(instance).to.have.property('tipoComissionamento');
        // expect(instance.tipoComissionamento).to.be(expectedValueLiteral);
      });

      it('should have the property percentual (base name: "Percentual")', function() {
        // TODO: update the code to test the property percentual
        expect(instance).to.have.property('percentual');
        // expect(instance.percentual).to.be(expectedValueLiteral);
      });

      it('should have the property periodicidade (base name: "Periodicidade")', function() {
        // TODO: update the code to test the property periodicidade
        expect(instance).to.have.property('periodicidade');
        // expect(instance.periodicidade).to.be(expectedValueLiteral);
      });

    });
  });

}));
