/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apiseguradora);
  }
}(this, function(expect, Apiseguradora) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('APISeguradoraContratoV1PropostaDocumento', function() {
      beforeEach(function() {
        instance = new Apiseguradora.APISeguradoraContratoV1PropostaDocumento();
      });

      it('should create an instance of APISeguradoraContratoV1PropostaDocumento', function() {
        // TODO: update the code to test APISeguradoraContratoV1PropostaDocumento
        expect(instance).to.be.a(Apiseguradora.APISeguradoraContratoV1PropostaDocumento);
      });

      it('should have the property naturezaDocumento (base name: "NaturezaDocumento")', function() {
        // TODO: update the code to test the property naturezaDocumento
        expect(instance).to.have.property('naturezaDocumento');
        // expect(instance.naturezaDocumento).to.be(expectedValueLiteral);
      });

      it('should have the property numeroDocumento (base name: "NumeroDocumento")', function() {
        // TODO: update the code to test the property numeroDocumento
        expect(instance).to.have.property('numeroDocumento');
        // expect(instance.numeroDocumento).to.be(expectedValueLiteral);
      });

      it('should have the property orgaoExpeditor (base name: "OrgaoExpeditor")', function() {
        // TODO: update the code to test the property orgaoExpeditor
        expect(instance).to.have.property('orgaoExpeditor');
        // expect(instance.orgaoExpeditor).to.be(expectedValueLiteral);
      });

      it('should have the property dataExpedicao (base name: "DataExpedicao")', function() {
        // TODO: update the code to test the property dataExpedicao
        expect(instance).to.have.property('dataExpedicao');
        // expect(instance.dataExpedicao).to.be(expectedValueLiteral);
      });

    });
  });

}));
