/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apiseguradora);
  }
}(this, function(expect, Apiseguradora) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('APISeguradoraContratoV1PropostaHierarquia', function() {
      beforeEach(function() {
        instance = new Apiseguradora.APISeguradoraContratoV1PropostaHierarquia();
      });

      it('should create an instance of APISeguradoraContratoV1PropostaHierarquia', function() {
        // TODO: update the code to test APISeguradoraContratoV1PropostaHierarquia
        expect(instance).to.be.a(Apiseguradora.APISeguradoraContratoV1PropostaHierarquia);
      });

      it('should have the property unidadeProducao (base name: "UnidadeProducao")', function() {
        // TODO: update the code to test the property unidadeProducao
        expect(instance).to.have.property('unidadeProducao');
        // expect(instance.unidadeProducao).to.be(expectedValueLiteral);
      });

      it('should have the property produtores (base name: "Produtores")', function() {
        // TODO: update the code to test the property produtores
        expect(instance).to.have.property('produtores');
        // expect(instance.produtores).to.be(expectedValueLiteral);
      });

    });
  });

}));
