/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apiseguradora);
  }
}(this, function(expect, Apiseguradora) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('APISeguradoraContratoV1ModeloNegocioFranquia', function() {
      beforeEach(function() {
        instance = new Apiseguradora.APISeguradoraContratoV1ModeloNegocioFranquia();
      });

      it('should create an instance of APISeguradoraContratoV1ModeloNegocioFranquia', function() {
        // TODO: update the code to test APISeguradoraContratoV1ModeloNegocioFranquia
        expect(instance).to.be.a(Apiseguradora.APISeguradoraContratoV1ModeloNegocioFranquia);
      });

      it('should have the property diasFranquia (base name: "diasFranquia")', function() {
        // TODO: update the code to test the property diasFranquia
        expect(instance).to.have.property('diasFranquia');
        // expect(instance.diasFranquia).to.be(expectedValueLiteral);
      });

      it('should have the property maximoDiariasPorEvento (base name: "maximoDiariasPorEvento")', function() {
        // TODO: update the code to test the property maximoDiariasPorEvento
        expect(instance).to.have.property('maximoDiariasPorEvento');
        // expect(instance.maximoDiariasPorEvento).to.be(expectedValueLiteral);
      });

      it('should have the property limiteDiarias (base name: "limiteDiarias")', function() {
        // TODO: update the code to test the property limiteDiarias
        expect(instance).to.have.property('limiteDiarias');
        // expect(instance.limiteDiarias).to.be(expectedValueLiteral);
      });

    });
  });

}));
