/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apiseguradora);
  }
}(this, function(expect, Apiseguradora) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('APISeguradoraImplementacaoESimProdutoCloneNegociacaoTeleUnderwritingDTO', function() {
      beforeEach(function() {
        instance = new Apiseguradora.APISeguradoraImplementacaoESimProdutoCloneNegociacaoTeleUnderwritingDTO();
      });

      it('should create an instance of APISeguradoraImplementacaoESimProdutoCloneNegociacaoTeleUnderwritingDTO', function() {
        // TODO: update the code to test APISeguradoraImplementacaoESimProdutoCloneNegociacaoTeleUnderwritingDTO
        expect(instance).to.be.a(Apiseguradora.APISeguradoraImplementacaoESimProdutoCloneNegociacaoTeleUnderwritingDTO);
      });

      it('should have the property capitalMaximo (base name: "CapitalMaximo")', function() {
        // TODO: update the code to test the property capitalMaximo
        expect(instance).to.have.property('capitalMaximo');
        // expect(instance.capitalMaximo).to.be(expectedValueLiteral);
      });

      it('should have the property capitalMinimo (base name: "CapitalMinimo")', function() {
        // TODO: update the code to test the property capitalMinimo
        expect(instance).to.have.property('capitalMinimo');
        // expect(instance.capitalMinimo).to.be(expectedValueLiteral);
      });

      it('should have the property fimVigencia (base name: "FimVigencia")', function() {
        // TODO: update the code to test the property fimVigencia
        expect(instance).to.have.property('fimVigencia');
        // expect(instance.fimVigencia).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "Id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property inicioVigencia (base name: "InicioVigencia")', function() {
        // TODO: update the code to test the property inicioVigencia
        expect(instance).to.have.property('inicioVigencia');
        // expect(instance.inicioVigencia).to.be(expectedValueLiteral);
      });

    });
  });

}));
