/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apiseguradora);
  }
}(this, function(expect, Apiseguradora) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('APISeguradoraContratoV1ModeloNegocioRegraCarenciaBeneficio', function() {
      beforeEach(function() {
        instance = new Apiseguradora.APISeguradoraContratoV1ModeloNegocioRegraCarenciaBeneficio();
      });

      it('should create an instance of APISeguradoraContratoV1ModeloNegocioRegraCarenciaBeneficio', function() {
        // TODO: update the code to test APISeguradoraContratoV1ModeloNegocioRegraCarenciaBeneficio
        expect(instance).to.be.a(Apiseguradora.APISeguradoraContratoV1ModeloNegocioRegraCarenciaBeneficio);
      });

      it('should have the property tipoId (base name: "tipoId")', function() {
        // TODO: update the code to test the property tipoId
        expect(instance).to.have.property('tipoId');
        // expect(instance.tipoId).to.be(expectedValueLiteral);
      });

      it('should have the property anulaCarenciaComDps (base name: "anulaCarenciaComDps")', function() {
        // TODO: update the code to test the property anulaCarenciaComDps
        expect(instance).to.have.property('anulaCarenciaComDps');
        // expect(instance.anulaCarenciaComDps).to.be(expectedValueLiteral);
      });

      it('should have the property quantidade (base name: "quantidade")', function() {
        // TODO: update the code to test the property quantidade
        expect(instance).to.have.property('quantidade');
        // expect(instance.quantidade).to.be(expectedValueLiteral);
      });

      it('should have the property progressivo (base name: "progressivo")', function() {
        // TODO: update the code to test the property progressivo
        expect(instance).to.have.property('progressivo');
        // expect(instance.progressivo).to.be(expectedValueLiteral);
      });

      it('should have the property tipoCarenciaBeneficio (base name: "tipoCarenciaBeneficio")', function() {
        // TODO: update the code to test the property tipoCarenciaBeneficio
        expect(instance).to.have.property('tipoCarenciaBeneficio');
        // expect(instance.tipoCarenciaBeneficio).to.be(expectedValueLiteral);
      });

    });
  });

}));
