/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apiseguradora);
  }
}(this, function(expect, Apiseguradora) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('APISeguradoraContratoV1SimulacaoSimulacaoModulo', function() {
      beforeEach(function() {
        instance = new Apiseguradora.APISeguradoraContratoV1SimulacaoSimulacaoModulo();
      });

      it('should create an instance of APISeguradoraContratoV1SimulacaoSimulacaoModulo', function() {
        // TODO: update the code to test APISeguradoraContratoV1SimulacaoSimulacaoModulo
        expect(instance).to.be.a(Apiseguradora.APISeguradoraContratoV1SimulacaoSimulacaoModulo);
      });

      it('should have the property modulo (base name: "modulo")', function() {
        // TODO: update the code to test the property modulo
        expect(instance).to.have.property('modulo');
        // expect(instance.modulo).to.be(expectedValueLiteral);
      });

      it('should have the property coberturas (base name: "coberturas")', function() {
        // TODO: update the code to test the property coberturas
        expect(instance).to.have.property('coberturas');
        // expect(instance.coberturas).to.be(expectedValueLiteral);
      });

      it('should have the property identificacao (base name: "identificacao")', function() {
        // TODO: update the code to test the property identificacao
        expect(instance).to.have.property('identificacao');
        // expect(instance.identificacao).to.be(expectedValueLiteral);
      });

      it('should have the property cargos (base name: "cargos")', function() {
        // TODO: update the code to test the property cargos
        expect(instance).to.have.property('cargos');
        // expect(instance.cargos).to.be(expectedValueLiteral);
      });

    });
  });

}));
