/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apiseguradora);
  }
}(this, function(expect, Apiseguradora) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('APISeguradoraContratoV1ModeloNegocioRenda', function() {
      beforeEach(function() {
        instance = new Apiseguradora.APISeguradoraContratoV1ModeloNegocioRenda();
      });

      it('should create an instance of APISeguradoraContratoV1ModeloNegocioRenda', function() {
        // TODO: update the code to test APISeguradoraContratoV1ModeloNegocioRenda
        expect(instance).to.be.a(Apiseguradora.APISeguradoraContratoV1ModeloNegocioRenda);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property tipo (base name: "tipo")', function() {
        // TODO: update the code to test the property tipo
        expect(instance).to.have.property('tipo');
        // expect(instance.tipo).to.be(expectedValueLiteral);
      });

      it('should have the property ehPadrao (base name: "ehPadrao")', function() {
        // TODO: update the code to test the property ehPadrao
        expect(instance).to.have.property('ehPadrao');
        // expect(instance.ehPadrao).to.be(expectedValueLiteral);
      });

      it('should have the property prazoInicial (base name: "prazoInicial")', function() {
        // TODO: update the code to test the property prazoInicial
        expect(instance).to.have.property('prazoInicial');
        // expect(instance.prazoInicial).to.be(expectedValueLiteral);
      });

      it('should have the property prazoFinal (base name: "prazoFinal")', function() {
        // TODO: update the code to test the property prazoFinal
        expect(instance).to.have.property('prazoFinal');
        // expect(instance.prazoFinal).to.be(expectedValueLiteral);
      });

      it('should have the property prazoPadrao (base name: "prazoPadrao")', function() {
        // TODO: update the code to test the property prazoPadrao
        expect(instance).to.have.property('prazoPadrao');
        // expect(instance.prazoPadrao).to.be(expectedValueLiteral);
      });

      it('should have the property idadeMaioridade (base name: "idadeMaioridade")', function() {
        // TODO: update the code to test the property idadeMaioridade
        expect(instance).to.have.property('idadeMaioridade');
        // expect(instance.idadeMaioridade).to.be(expectedValueLiteral);
      });

    });
  });

}));
