/*
 * API.Seguradora
 * Serviços de Negócios expostos através de RESTful services, para integrações com parceiros e agilidade no desenvolvimento interno de softwares da companhia.
 *
 * OpenAPI spec version: v1
 * Contact: integracaosistemas@mongeralaegon.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Apiseguradora);
  }
}(this, function(expect, Apiseguradora) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('APISeguradoraImplementacaoServicoDadosModeloNegocio', function() {
      beforeEach(function() {
        instance = new Apiseguradora.APISeguradoraImplementacaoServicoDadosModeloNegocio();
      });

      it('should create an instance of APISeguradoraImplementacaoServicoDadosModeloNegocio', function() {
        // TODO: update the code to test APISeguradoraImplementacaoServicoDadosModeloNegocio
        expect(instance).to.be.a(Apiseguradora.APISeguradoraImplementacaoServicoDadosModeloNegocio);
      });

      it('should have the property codigoModelo (base name: "codigoModelo")', function() {
        // TODO: update the code to test the property codigoModelo
        expect(instance).to.have.property('codigoModelo');
        // expect(instance.codigoModelo).to.be(expectedValueLiteral);
      });

      it('should have the property negociacaoId (base name: "negociacaoId")', function() {
        // TODO: update the code to test the property negociacaoId
        expect(instance).to.have.property('negociacaoId');
        // expect(instance.negociacaoId).to.be(expectedValueLiteral);
      });

      it('should have the property cnpjParceiro (base name: "cnpjParceiro")', function() {
        // TODO: update the code to test the property cnpjParceiro
        expect(instance).to.have.property('cnpjParceiro');
        // expect(instance.cnpjParceiro).to.be(expectedValueLiteral);
      });

      it('should have the property loginUsuario (base name: "loginUsuario")', function() {
        // TODO: update the code to test the property loginUsuario
        expect(instance).to.have.property('loginUsuario');
        // expect(instance.loginUsuario).to.be(expectedValueLiteral);
      });

      it('should have the property dadosModelo (base name: "dadosModelo")', function() {
        // TODO: update the code to test the property dadosModelo
        expect(instance).to.have.property('dadosModelo');
        // expect(instance.dadosModelo).to.be(expectedValueLiteral);
      });

    });
  });

}));
